# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminedit.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AdminEdit(object):
    def setupUi(self, AdminEdit):
        AdminEdit.setObjectName(_fromUtf8("AdminEdit"))
        AdminEdit.resize(446, 289)
        AdminEdit.setStyleSheet(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(AdminEdit)
        self.label_6.setGeometry(QtCore.QRect(160, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_6.setFrameShadow(QtGui.QFrame.Plain)
        self.label_6.setLineWidth(1)
        self.label_6.setMidLineWidth(0)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.layoutWidget = QtGui.QWidget(AdminEdit)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 60, 381, 131))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setFrameShadow(QtGui.QFrame.Plain)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.admin_edit_id = QtGui.QLineEdit(self.layoutWidget)
        self.admin_edit_id.setReadOnly(True)
        self.admin_edit_id.setObjectName(_fromUtf8("admin_edit_id"))
        self.gridLayout.addWidget(self.admin_edit_id, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtGui.QFrame.Plain)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.admin_edit_username = QtGui.QLineEdit(self.layoutWidget)
        self.admin_edit_username.setReadOnly(True)
        self.admin_edit_username.setObjectName(_fromUtf8("admin_edit_username"))
        self.gridLayout.addWidget(self.admin_edit_username, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtGui.QFrame.Plain)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.admin_edit_password = QtGui.QLineEdit(self.layoutWidget)
        self.admin_edit_password.setStyleSheet(_fromUtf8(""))
        self.admin_edit_password.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.admin_edit_password.setEchoMode(QtGui.QLineEdit.Password)
        self.admin_edit_password.setObjectName(_fromUtf8("admin_edit_password"))
        self.gridLayout.addWidget(self.admin_edit_password, 2, 1, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(AdminEdit)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 210, 301, 71))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.admin_edit_error = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.admin_edit_error.setFont(font)
        self.admin_edit_error.setText(_fromUtf8(""))
        self.admin_edit_error.setAlignment(QtCore.Qt.AlignCenter)
        self.admin_edit_error.setObjectName(_fromUtf8("admin_edit_error"))
        self.verticalLayout.addWidget(self.admin_edit_error)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.admin_delete_btn = QtGui.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.admin_delete_btn.setFont(font)
        self.admin_delete_btn.setCheckable(False)
        self.admin_delete_btn.setAutoDefault(True)
        self.admin_delete_btn.setObjectName(_fromUtf8("admin_delete_btn"))
        self.horizontalLayout.addWidget(self.admin_delete_btn)
        self.admin_edit_cancel_btn = QtGui.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.admin_edit_cancel_btn.setFont(font)
        self.admin_edit_cancel_btn.setAutoDefault(True)
        self.admin_edit_cancel_btn.setObjectName(_fromUtf8("admin_edit_cancel_btn"))
        self.horizontalLayout.addWidget(self.admin_edit_cancel_btn)
        self.admin_edit_btn = QtGui.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.admin_edit_btn.setFont(font)
        self.admin_edit_btn.setAutoDefault(True)
        self.admin_edit_btn.setFlat(False)
        self.admin_edit_btn.setObjectName(_fromUtf8("admin_edit_btn"))
        self.horizontalLayout.addWidget(self.admin_edit_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(AdminEdit)
        QtCore.QMetaObject.connectSlotsByName(AdminEdit)

    def retranslateUi(self, AdminEdit):
        AdminEdit.setWindowTitle(_translate("AdminEdit", "MeX - Edit Admin", None))
        self.label_6.setText(_translate("AdminEdit", "Edit Admin", None))
        self.label.setText(_translate("AdminEdit", "ID:", None))
        self.admin_edit_id.setPlaceholderText(_translate("AdminEdit", "ID", None))
        self.label_2.setText(_translate("AdminEdit", "Username:", None))
        self.admin_edit_username.setPlaceholderText(_translate("AdminEdit", "username", None))
        self.label_3.setText(_translate("AdminEdit", "Password:", None))
        self.admin_edit_password.setPlaceholderText(_translate("AdminEdit", "password", None))
        self.admin_delete_btn.setText(_translate("AdminEdit", "Delete", None))
        self.admin_edit_cancel_btn.setText(_translate("AdminEdit", "Close", None))
        self.admin_edit_btn.setText(_translate("AdminEdit", "Save", None))

