# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/catedit.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CatEdit(object):
    def setupUi(self, CatEdit):
        CatEdit.setObjectName(_fromUtf8("CatEdit"))
        CatEdit.resize(504, 326)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/img/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CatEdit.setWindowIcon(icon)
        CatEdit.setStyleSheet(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(CatEdit)
        self.label_6.setGeometry(QtCore.QRect(150, 10, 201, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_6.setFrameShadow(QtGui.QFrame.Plain)
        self.label_6.setLineWidth(1)
        self.label_6.setMidLineWidth(0)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.layoutWidget = QtGui.QWidget(CatEdit)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 230, 431, 81))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.cat_edit_error = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cat_edit_error.setFont(font)
        self.cat_edit_error.setText(_fromUtf8(""))
        self.cat_edit_error.setAlignment(QtCore.Qt.AlignCenter)
        self.cat_edit_error.setWordWrap(True)
        self.cat_edit_error.setObjectName(_fromUtf8("cat_edit_error"))
        self.verticalLayout.addWidget(self.cat_edit_error)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cat_delete_btn = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cat_delete_btn.setFont(font)
        self.cat_delete_btn.setCheckable(False)
        self.cat_delete_btn.setAutoDefault(True)
        self.cat_delete_btn.setObjectName(_fromUtf8("cat_delete_btn"))
        self.horizontalLayout.addWidget(self.cat_delete_btn)
        self.cat_edit_cancel_btn = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cat_edit_cancel_btn.setFont(font)
        self.cat_edit_cancel_btn.setAutoDefault(True)
        self.cat_edit_cancel_btn.setObjectName(_fromUtf8("cat_edit_cancel_btn"))
        self.horizontalLayout.addWidget(self.cat_edit_cancel_btn)
        self.cat_edit_btn = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cat_edit_btn.setFont(font)
        self.cat_edit_btn.setAutoDefault(True)
        self.cat_edit_btn.setFlat(False)
        self.cat_edit_btn.setObjectName(_fromUtf8("cat_edit_btn"))
        self.horizontalLayout.addWidget(self.cat_edit_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.layoutWidget1 = QtGui.QWidget(CatEdit)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 70, 481, 151))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setFrameShadow(QtGui.QFrame.Plain)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_6.addWidget(self.label)
        self.cat_edit_id = QtGui.QLineEdit(self.layoutWidget1)
        self.cat_edit_id.setReadOnly(True)
        self.cat_edit_id.setObjectName(_fromUtf8("cat_edit_id"))
        self.horizontalLayout_6.addWidget(self.cat_edit_id)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtGui.QFrame.Plain)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.cat_edit_name = QtGui.QLineEdit(self.layoutWidget1)
        self.cat_edit_name.setObjectName(_fromUtf8("cat_edit_name"))
        self.horizontalLayout_5.addWidget(self.cat_edit_name)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtGui.QFrame.Plain)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.cat_edit_custom_id = QtGui.QLineEdit(self.layoutWidget1)
        self.cat_edit_custom_id.setInputMethodHints(QtCore.Qt.ImhNone)
        self.cat_edit_custom_id.setObjectName(_fromUtf8("cat_edit_custom_id"))
        self.horizontalLayout_4.addWidget(self.cat_edit_custom_id)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)

        self.retranslateUi(CatEdit)
        QtCore.QMetaObject.connectSlotsByName(CatEdit)

    def retranslateUi(self, CatEdit):
        CatEdit.setWindowTitle(_translate("CatEdit", "Mex LMS - Category Edit", None))
        self.label_6.setText(_translate("CatEdit", "Edit Category", None))
        self.cat_delete_btn.setText(_translate("CatEdit", "Delete", None))
        self.cat_edit_cancel_btn.setText(_translate("CatEdit", "Close", None))
        self.cat_edit_btn.setText(_translate("CatEdit", "Save", None))
        self.label.setText(_translate("CatEdit", "ID", None))
        self.cat_edit_id.setPlaceholderText(_translate("CatEdit", "ID", None))
        self.label_2.setText(_translate("CatEdit", "Name", None))
        self.cat_edit_name.setPlaceholderText(_translate("CatEdit", "Name", None))
        self.label_3.setText(_translate("CatEdit", "Custom ID", None))
        self.cat_edit_custom_id.setPlaceholderText(_translate("CatEdit", "Custom ID", None))

import resources_rc
