# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lmsborrowedit.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BorrowEdit(object):
    def setupUi(self, BorrowEdit):
        BorrowEdit.setObjectName(_fromUtf8("BorrowEdit"))
        BorrowEdit.resize(509, 385)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BorrowEdit.setWindowIcon(icon)
        BorrowEdit.setStyleSheet(_fromUtf8(""))
        self.borrow_edit_book_id = QtGui.QLineEdit(BorrowEdit)
        self.borrow_edit_book_id.setGeometry(QtCore.QRect(150, 100, 221, 32))
        self.borrow_edit_book_id.setObjectName(_fromUtf8("borrow_edit_book_id"))
        self.borrow_edit_member_id = QtGui.QLineEdit(BorrowEdit)
        self.borrow_edit_member_id.setGeometry(QtCore.QRect(150, 140, 221, 32))
        self.borrow_edit_member_id.setInputMethodHints(QtCore.Qt.ImhNone)
        self.borrow_edit_member_id.setObjectName(_fromUtf8("borrow_edit_member_id"))
        self.borrow_edit_active = QtGui.QCheckBox(BorrowEdit)
        self.borrow_edit_active.setGeometry(QtCore.QRect(150, 260, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.borrow_edit_active.setFont(font)
        self.borrow_edit_active.setChecked(False)
        self.borrow_edit_active.setTristate(False)
        self.borrow_edit_active.setObjectName(_fromUtf8("borrow_edit_active"))
        self.label_2 = QtGui.QLabel(BorrowEdit)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 81, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtGui.QFrame.Plain)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(BorrowEdit)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 101, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtGui.QFrame.Plain)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(BorrowEdit)
        self.label_4.setGeometry(QtCore.QRect(80, 180, 51, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_4.setFrameShadow(QtGui.QFrame.Plain)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(BorrowEdit)
        self.label_5.setGeometry(QtCore.QRect(90, 220, 41, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_5.setFrameShadow(QtGui.QFrame.Plain)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(BorrowEdit)
        self.label_6.setGeometry(QtCore.QRect(180, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_6.setFrameShadow(QtGui.QFrame.Plain)
        self.label_6.setLineWidth(1)
        self.label_6.setMidLineWidth(0)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.borrow_edit_btn = QtGui.QPushButton(BorrowEdit)
        self.borrow_edit_btn.setGeometry(QtCore.QRect(320, 330, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.borrow_edit_btn.setFont(font)
        self.borrow_edit_btn.setAutoDefault(True)
        self.borrow_edit_btn.setFlat(False)
        self.borrow_edit_btn.setObjectName(_fromUtf8("borrow_edit_btn"))
        self.borrow_edit_cancel_btn = QtGui.QPushButton(BorrowEdit)
        self.borrow_edit_cancel_btn.setGeometry(QtCore.QRect(220, 330, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.borrow_edit_cancel_btn.setFont(font)
        self.borrow_edit_cancel_btn.setAutoDefault(True)
        self.borrow_edit_cancel_btn.setObjectName(_fromUtf8("borrow_edit_cancel_btn"))
        self.borrow_delete_btn = QtGui.QPushButton(BorrowEdit)
        self.borrow_delete_btn.setGeometry(QtCore.QRect(120, 330, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.borrow_delete_btn.setFont(font)
        self.borrow_delete_btn.setCheckable(False)
        self.borrow_delete_btn.setAutoDefault(True)
        self.borrow_delete_btn.setObjectName(_fromUtf8("borrow_delete_btn"))
        self.borrow_edit_error = QtGui.QLabel(BorrowEdit)
        self.borrow_edit_error.setGeometry(QtCore.QRect(150, 289, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.borrow_edit_error.setFont(font)
        self.borrow_edit_error.setText(_fromUtf8(""))
        self.borrow_edit_error.setObjectName(_fromUtf8("borrow_edit_error"))
        self.borrow_edit_id = QtGui.QLineEdit(BorrowEdit)
        self.borrow_edit_id.setGeometry(QtCore.QRect(150, 60, 221, 32))
        self.borrow_edit_id.setReadOnly(True)
        self.borrow_edit_id.setObjectName(_fromUtf8("borrow_edit_id"))
        self.label = QtGui.QLabel(BorrowEdit)
        self.label.setGeometry(QtCore.QRect(100, 60, 31, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setFrameShadow(QtGui.QFrame.Plain)
        self.label.setObjectName(_fromUtf8("label"))
        self.borrow_edit_start = QtGui.QDateEdit(BorrowEdit)
        self.borrow_edit_start.setGeometry(QtCore.QRect(150, 180, 221, 32))
        self.borrow_edit_start.setCalendarPopup(True)
        self.borrow_edit_start.setObjectName(_fromUtf8("borrow_edit_start"))
        self.borrow_edit_end = QtGui.QDateEdit(BorrowEdit)
        self.borrow_edit_end.setGeometry(QtCore.QRect(150, 220, 221, 32))
        self.borrow_edit_end.setCalendarPopup(True)
        self.borrow_edit_end.setObjectName(_fromUtf8("borrow_edit_end"))

        self.retranslateUi(BorrowEdit)
        QtCore.QMetaObject.connectSlotsByName(BorrowEdit)

    def retranslateUi(self, BorrowEdit):
        BorrowEdit.setWindowTitle(_translate("BorrowEdit", "MeX LMS - Edit borrow", None))
        self.borrow_edit_book_id.setPlaceholderText(_translate("BorrowEdit", "Book ID", None))
        self.borrow_edit_member_id.setPlaceholderText(_translate("BorrowEdit", "Member ID", None))
        self.borrow_edit_active.setText(_translate("BorrowEdit", "Active", None))
        self.label_2.setText(_translate("BorrowEdit", "Book ID", None))
        self.label_3.setText(_translate("BorrowEdit", "Member ID", None))
        self.label_4.setText(_translate("BorrowEdit", "Start", None))
        self.label_5.setText(_translate("BorrowEdit", "End", None))
        self.label_6.setText(_translate("BorrowEdit", "Edit Borrow", None))
        self.borrow_edit_btn.setText(_translate("BorrowEdit", "Save", None))
        self.borrow_edit_cancel_btn.setText(_translate("BorrowEdit", "Close", None))
        self.borrow_delete_btn.setText(_translate("BorrowEdit", "Delete", None))
        self.borrow_edit_id.setPlaceholderText(_translate("BorrowEdit", "ID", None))
        self.label.setText(_translate("BorrowEdit", "ID", None))

