# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lmsgui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(786, 587)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.main_tabs = QtGui.QTabWidget(self.centralwidget)
        self.main_tabs.setGeometry(QtCore.QRect(0, 0, 781, 541))
        self.main_tabs.setObjectName(_fromUtf8("main_tabs"))
        self.books_tab = QtGui.QWidget()
        self.books_tab.setObjectName(_fromUtf8("books_tab"))
        self.groupBox_4 = QtGui.QGroupBox(self.books_tab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 0, 761, 91))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.book_add_btn = QtGui.QPushButton(self.groupBox_4)
        self.book_add_btn.setGeometry(QtCore.QRect(610, 20, 101, 31))
        self.book_add_btn.setAutoDefault(True)
        self.book_add_btn.setObjectName(_fromUtf8("book_add_btn"))
        self.book_add_copies = QtGui.QLineEdit(self.groupBox_4)
        self.book_add_copies.setGeometry(QtCore.QRect(20, 60, 211, 32))
        self.book_add_copies.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.book_add_copies.setText(_fromUtf8(""))
        self.book_add_copies.setObjectName(_fromUtf8("book_add_copies"))
        self.book_add_title = QtGui.QLineEdit(self.groupBox_4)
        self.book_add_title.setGeometry(QtCore.QRect(20, 20, 211, 32))
        self.book_add_title.setObjectName(_fromUtf8("book_add_title"))
        self.book_add_author = QtGui.QLineEdit(self.groupBox_4)
        self.book_add_author.setGeometry(QtCore.QRect(240, 20, 201, 32))
        self.book_add_author.setInputMethodHints(QtCore.Qt.ImhNone)
        self.book_add_author.setObjectName(_fromUtf8("book_add_author"))
        self.book_add_publisher = QtGui.QLineEdit(self.groupBox_4)
        self.book_add_publisher.setGeometry(QtCore.QRect(450, 20, 151, 32))
        self.book_add_publisher.setInputMethodHints(QtCore.Qt.ImhNone)
        self.book_add_publisher.setObjectName(_fromUtf8("book_add_publisher"))
        self.book_add_error = QtGui.QLabel(self.groupBox_4)
        self.book_add_error.setGeometry(QtCore.QRect(520, 60, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.book_add_error.setFont(font)
        self.book_add_error.setStyleSheet(_fromUtf8("QLabel {\n"
"color:rgb(255, 0, 0);\n"
"}"))
        self.book_add_error.setText(_fromUtf8(""))
        self.book_add_error.setTextFormat(QtCore.Qt.RichText)
        self.book_add_error.setObjectName(_fromUtf8("book_add_error"))
        self.book_add_available = QtGui.QCheckBox(self.groupBox_4)
        self.book_add_available.setGeometry(QtCore.QRect(240, 60, 91, 25))
        self.book_add_available.setChecked(True)
        self.book_add_available.setObjectName(_fromUtf8("book_add_available"))
        self.books_table = QtGui.QTableWidget(self.books_tab)
        self.books_table.setGeometry(QtCore.QRect(0, 170, 611, 341))
        self.books_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.books_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.books_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.books_table.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.books_table.setObjectName(_fromUtf8("books_table"))
        self.books_table.setColumnCount(6)
        self.books_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.books_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.books_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.books_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.books_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.books_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.books_table.setHorizontalHeaderItem(5, item)
        self.books_table.verticalHeader().setVisible(False)
        self.groupBox_2 = QtGui.QGroupBox(self.books_tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 110, 761, 51))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.book_search_btn = QtGui.QPushButton(self.groupBox_2)
        self.book_search_btn.setGeometry(QtCore.QRect(670, 20, 82, 31))
        self.book_search_btn.setAutoDefault(True)
        self.book_search_btn.setObjectName(_fromUtf8("book_search_btn"))
        self.book_search_id = QtGui.QLineEdit(self.groupBox_2)
        self.book_search_id.setGeometry(QtCore.QRect(10, 20, 41, 32))
        self.book_search_id.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.book_search_id.setObjectName(_fromUtf8("book_search_id"))
        self.book_search_title = QtGui.QLineEdit(self.groupBox_2)
        self.book_search_title.setGeometry(QtCore.QRect(50, 20, 191, 32))
        self.book_search_title.setObjectName(_fromUtf8("book_search_title"))
        self.book_search_author = QtGui.QLineEdit(self.groupBox_2)
        self.book_search_author.setGeometry(QtCore.QRect(240, 20, 171, 32))
        self.book_search_author.setInputMethodHints(QtCore.Qt.ImhNone)
        self.book_search_author.setObjectName(_fromUtf8("book_search_author"))
        self.book_search_publisher = QtGui.QLineEdit(self.groupBox_2)
        self.book_search_publisher.setGeometry(QtCore.QRect(410, 20, 141, 32))
        self.book_search_publisher.setInputMethodHints(QtCore.Qt.ImhNone)
        self.book_search_publisher.setObjectName(_fromUtf8("book_search_publisher"))
        self.book_search_available = QtGui.QCheckBox(self.groupBox_2)
        self.book_search_available.setGeometry(QtCore.QRect(560, 10, 91, 25))
        self.book_search_available.setChecked(True)
        self.book_search_available.setObjectName(_fromUtf8("book_search_available"))
        self.book_search_not_available = QtGui.QCheckBox(self.groupBox_2)
        self.book_search_not_available.setGeometry(QtCore.QRect(560, 30, 111, 25))
        self.book_search_not_available.setChecked(True)
        self.book_search_not_available.setObjectName(_fromUtf8("book_search_not_available"))
        self.line_2 = QtGui.QFrame(self.books_tab)
        self.line_2.setGeometry(QtCore.QRect(-3, 96, 781, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/book.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_tabs.addTab(self.books_tab, icon, _fromUtf8(""))
        self.members_tab = QtGui.QWidget()
        self.members_tab.setObjectName(_fromUtf8("members_tab"))
        self.groupBox_9 = QtGui.QGroupBox(self.members_tab)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 0, 761, 61))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.member_add_btn = QtGui.QPushButton(self.groupBox_9)
        self.member_add_btn.setGeometry(QtCore.QRect(470, 20, 101, 31))
        self.member_add_btn.setAutoDefault(True)
        self.member_add_btn.setObjectName(_fromUtf8("member_add_btn"))
        self.member_add_name = QtGui.QLineEdit(self.groupBox_9)
        self.member_add_name.setGeometry(QtCore.QRect(20, 20, 161, 32))
        self.member_add_name.setObjectName(_fromUtf8("member_add_name"))
        self.member_add_email = QtGui.QLineEdit(self.groupBox_9)
        self.member_add_email.setGeometry(QtCore.QRect(180, 20, 161, 32))
        self.member_add_email.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.member_add_email.setObjectName(_fromUtf8("member_add_email"))
        self.member_add_mob = QtGui.QLineEdit(self.groupBox_9)
        self.member_add_mob.setGeometry(QtCore.QRect(340, 20, 121, 32))
        self.member_add_mob.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.member_add_mob.setObjectName(_fromUtf8("member_add_mob"))
        self.member_add_error = QtGui.QLabel(self.groupBox_9)
        self.member_add_error.setGeometry(QtCore.QRect(580, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.member_add_error.setFont(font)
        self.member_add_error.setStyleSheet(_fromUtf8("QLabel {\n"
"color:rgb(255, 0, 0);\n"
"}"))
        self.member_add_error.setText(_fromUtf8(""))
        self.member_add_error.setTextFormat(QtCore.Qt.RichText)
        self.member_add_error.setObjectName(_fromUtf8("member_add_error"))
        self.groupBox = QtGui.QGroupBox(self.members_tab)
        self.groupBox.setGeometry(QtCore.QRect(520, 80, 251, 421))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.member_search_id = QtGui.QLineEdit(self.groupBox)
        self.member_search_id.setGeometry(QtCore.QRect(10, 30, 241, 32))
        self.member_search_id.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.member_search_id.setObjectName(_fromUtf8("member_search_id"))
        self.member_search_name = QtGui.QLineEdit(self.groupBox)
        self.member_search_name.setGeometry(QtCore.QRect(10, 70, 241, 32))
        self.member_search_name.setObjectName(_fromUtf8("member_search_name"))
        self.member_search_email = QtGui.QLineEdit(self.groupBox)
        self.member_search_email.setGeometry(QtCore.QRect(10, 110, 241, 32))
        self.member_search_email.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.member_search_email.setObjectName(_fromUtf8("member_search_email"))
        self.member_search_mob = QtGui.QLineEdit(self.groupBox)
        self.member_search_mob.setGeometry(QtCore.QRect(10, 150, 241, 32))
        self.member_search_mob.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.member_search_mob.setObjectName(_fromUtf8("member_search_mob"))
        self.member_search_btn = QtGui.QPushButton(self.groupBox)
        self.member_search_btn.setGeometry(QtCore.QRect(80, 190, 101, 31))
        self.member_search_btn.setAutoDefault(True)
        self.member_search_btn.setObjectName(_fromUtf8("member_search_btn"))
        self.members_table = QtGui.QTableWidget(self.members_tab)
        self.members_table.setGeometry(QtCore.QRect(0, 80, 511, 421))
        self.members_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.members_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.members_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.members_table.setObjectName(_fromUtf8("members_table"))
        self.members_table.setColumnCount(5)
        self.members_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(4, item)
        self.members_table.verticalHeader().setVisible(False)
        self.line = QtGui.QFrame(self.members_tab)
        self.line.setGeometry(QtCore.QRect(0, 56, 771, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_3 = QtGui.QFrame(self.members_tab)
        self.line_3.setGeometry(QtCore.QRect(510, 70, 16, 441))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/member.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_tabs.addTab(self.members_tab, icon1, _fromUtf8(""))
        self.borrows_tab = QtGui.QWidget()
        self.borrows_tab.setObjectName(_fromUtf8("borrows_tab"))
        self.groupBox_10 = QtGui.QGroupBox(self.borrows_tab)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 0, 761, 91))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.borrow_add_btn = QtGui.QPushButton(self.groupBox_10)
        self.borrow_add_btn.setGeometry(QtCore.QRect(560, 20, 101, 31))
        self.borrow_add_btn.setAutoDefault(True)
        self.borrow_add_btn.setObjectName(_fromUtf8("borrow_add_btn"))
        self.borrow_add_book_id = QtGui.QLineEdit(self.groupBox_10)
        self.borrow_add_book_id.setGeometry(QtCore.QRect(20, 20, 181, 32))
        self.borrow_add_book_id.setObjectName(_fromUtf8("borrow_add_book_id"))
        self.borrow_add_member_id = QtGui.QLineEdit(self.groupBox_10)
        self.borrow_add_member_id.setGeometry(QtCore.QRect(220, 20, 181, 32))
        self.borrow_add_member_id.setInputMethodHints(QtCore.Qt.ImhNone)
        self.borrow_add_member_id.setObjectName(_fromUtf8("borrow_add_member_id"))
        self.borrow_add_error = QtGui.QLabel(self.groupBox_10)
        self.borrow_add_error.setGeometry(QtCore.QRect(410, 60, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.borrow_add_error.setFont(font)
        self.borrow_add_error.setStyleSheet(_fromUtf8("QLabel {\n"
"color:rgb(255, 0, 0);\n"
"}"))
        self.borrow_add_error.setText(_fromUtf8(""))
        self.borrow_add_error.setTextFormat(QtCore.Qt.RichText)
        self.borrow_add_error.setObjectName(_fromUtf8("borrow_add_error"))
        self.borrow_add_active = QtGui.QCheckBox(self.groupBox_10)
        self.borrow_add_active.setGeometry(QtCore.QRect(420, 20, 91, 25))
        self.borrow_add_active.setChecked(True)
        self.borrow_add_active.setObjectName(_fromUtf8("borrow_add_active"))
        self.borrow_add_start = QtGui.QDateEdit(self.groupBox_10)
        self.borrow_add_start.setGeometry(QtCore.QRect(80, 60, 121, 32))
        self.borrow_add_start.setCalendarPopup(True)
        self.borrow_add_start.setObjectName(_fromUtf8("borrow_add_start"))
        self.borrow_add_end = QtGui.QDateEdit(self.groupBox_10)
        self.borrow_add_end.setGeometry(QtCore.QRect(270, 60, 131, 32))
        self.borrow_add_end.setCalendarPopup(True)
        self.borrow_add_end.setObjectName(_fromUtf8("borrow_add_end"))
        self.label = QtGui.QLabel(self.groupBox_10)
        self.label.setGeometry(QtCore.QRect(20, 60, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox_10)
        self.label_2.setGeometry(QtCore.QRect(220, 60, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.borrows_table = QtGui.QTableWidget(self.borrows_tab)
        self.borrows_table.setGeometry(QtCore.QRect(0, 250, 781, 251))
        self.borrows_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.borrows_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.borrows_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.borrows_table.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.borrows_table.setObjectName(_fromUtf8("borrows_table"))
        self.borrows_table.setColumnCount(8)
        self.borrows_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.borrows_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.borrows_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.borrows_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.borrows_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.borrows_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.borrows_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.borrows_table.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.borrows_table.setHorizontalHeaderItem(7, item)
        self.borrows_table.verticalHeader().setVisible(False)
        self.groupBox_3 = QtGui.QGroupBox(self.borrows_tab)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 110, 761, 131))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.borrow_search_btn = QtGui.QPushButton(self.groupBox_3)
        self.borrow_search_btn.setGeometry(QtCore.QRect(610, 40, 131, 51))
        self.borrow_search_btn.setAutoDefault(True)
        self.borrow_search_btn.setObjectName(_fromUtf8("borrow_search_btn"))
        self.borrow_search_id = QtGui.QLineEdit(self.groupBox_3)
        self.borrow_search_id.setGeometry(QtCore.QRect(20, 20, 41, 32))
        self.borrow_search_id.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.borrow_search_id.setObjectName(_fromUtf8("borrow_search_id"))
        self.borrow_search_active = QtGui.QCheckBox(self.groupBox_3)
        self.borrow_search_active.setGeometry(QtCore.QRect(480, 70, 71, 25))
        self.borrow_search_active.setChecked(True)
        self.borrow_search_active.setObjectName(_fromUtf8("borrow_search_active"))
        self.borrow_search_not_active = QtGui.QCheckBox(self.groupBox_3)
        self.borrow_search_not_active.setGeometry(QtCore.QRect(480, 90, 101, 25))
        self.borrow_search_not_active.setChecked(True)
        self.borrow_search_not_active.setObjectName(_fromUtf8("borrow_search_not_active"))
        self.borrow_search_book_id = QtGui.QLineEdit(self.groupBox_3)
        self.borrow_search_book_id.setGeometry(QtCore.QRect(80, 20, 61, 32))
        self.borrow_search_book_id.setObjectName(_fromUtf8("borrow_search_book_id"))
        self.borrow_search_member_id = QtGui.QLineEdit(self.groupBox_3)
        self.borrow_search_member_id.setGeometry(QtCore.QRect(340, 20, 81, 32))
        self.borrow_search_member_id.setInputMethodHints(QtCore.Qt.ImhNone)
        self.borrow_search_member_id.setObjectName(_fromUtf8("borrow_search_member_id"))
        self.borrow_search_start = QtGui.QDateEdit(self.groupBox_3)
        self.borrow_search_start.setGeometry(QtCore.QRect(160, 60, 131, 32))
        self.borrow_search_start.setCalendarPopup(True)
        self.borrow_search_start.setObjectName(_fromUtf8("borrow_search_start"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(120, 60, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.borrow_search_end = QtGui.QDateEdit(self.groupBox_3)
        self.borrow_search_end.setGeometry(QtCore.QRect(340, 60, 131, 32))
        self.borrow_search_end.setCalendarPopup(True)
        self.borrow_search_end.setObjectName(_fromUtf8("borrow_search_end"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(310, 60, 31, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.borrow_search_to = QtGui.QDateEdit(self.groupBox_3)
        self.borrow_search_to.setGeometry(QtCore.QRect(340, 100, 131, 32))
        self.borrow_search_to.setCalendarPopup(True)
        self.borrow_search_to.setObjectName(_fromUtf8("borrow_search_to"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(310, 100, 31, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(120, 100, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.borrow_search_from = QtGui.QDateEdit(self.groupBox_3)
        self.borrow_search_from.setGeometry(QtCore.QRect(160, 100, 131, 32))
        self.borrow_search_from.setCalendarPopup(True)
        self.borrow_search_from.setObjectName(_fromUtf8("borrow_search_from"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(0, 100, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.borrow_search_member_name = QtGui.QLineEdit(self.groupBox_3)
        self.borrow_search_member_name.setGeometry(QtCore.QRect(420, 20, 181, 32))
        self.borrow_search_member_name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.borrow_search_member_name.setObjectName(_fromUtf8("borrow_search_member_name"))
        self.borrow_search_book_title = QtGui.QLineEdit(self.groupBox_3)
        self.borrow_search_book_title.setGeometry(QtCore.QRect(140, 20, 181, 32))
        self.borrow_search_book_title.setObjectName(_fromUtf8("borrow_search_book_title"))
        self.borrow_search_btn.raise_()
        self.borrow_search_id.raise_()
        self.borrow_search_active.raise_()
        self.borrow_search_not_active.raise_()
        self.borrow_add_book_id.raise_()
        self.borrow_add_member_id.raise_()
        self.borrow_add_start.raise_()
        self.borrow_search_book_id.raise_()
        self.borrow_search_member_id.raise_()
        self.borrow_search_start.raise_()
        self.label_3.raise_()
        self.borrow_search_end.raise_()
        self.label_4.raise_()
        self.borrow_search_to.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.borrow_search_from.raise_()
        self.label_11.raise_()
        self.borrows_table.raise_()
        self.borrow_search_member_name.raise_()
        self.borrow_search_book_title.raise_()
        self.line_6 = QtGui.QFrame(self.borrows_tab)
        self.line_6.setGeometry(QtCore.QRect(0, 90, 781, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("img/borrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_tabs.addTab(self.borrows_tab, icon2, _fromUtf8(""))
        self.admin_tab = QtGui.QWidget()
        self.admin_tab.setObjectName(_fromUtf8("admin_tab"))
        self.groupBox_5 = QtGui.QGroupBox(self.admin_tab)
        self.groupBox_5.setGeometry(QtCore.QRect(300, 10, 391, 221))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.admin_edit_btn = QtGui.QPushButton(self.groupBox_5)
        self.admin_edit_btn.setGeometry(QtCore.QRect(70, 160, 111, 41))
        self.admin_edit_btn.setAutoDefault(True)
        self.admin_edit_btn.setObjectName(_fromUtf8("admin_edit_btn"))
        self.admin_edit_error = QtGui.QLabel(self.groupBox_5)
        self.admin_edit_error.setGeometry(QtCore.QRect(190, 170, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.admin_edit_error.setFont(font)
        self.admin_edit_error.setStyleSheet(_fromUtf8("QLabel {\n"
"color:rgb(255, 0, 0);\n"
"}"))
        self.admin_edit_error.setText(_fromUtf8(""))
        self.admin_edit_error.setTextFormat(QtCore.Qt.RichText)
        self.admin_edit_error.setObjectName(_fromUtf8("admin_edit_error"))
        self.admin_edit_new_password = QtGui.QLineEdit(self.groupBox_5)
        self.admin_edit_new_password.setGeometry(QtCore.QRect(70, 110, 271, 41))
        self.admin_edit_new_password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.admin_edit_new_password.setText(_fromUtf8(""))
        self.admin_edit_new_password.setEchoMode(QtGui.QLineEdit.Password)
        self.admin_edit_new_password.setObjectName(_fromUtf8("admin_edit_new_password"))
        self.admin_edit_old_password = QtGui.QLineEdit(self.groupBox_5)
        self.admin_edit_old_password.setGeometry(QtCore.QRect(70, 70, 271, 41))
        self.admin_edit_old_password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.admin_edit_old_password.setText(_fromUtf8(""))
        self.admin_edit_old_password.setEchoMode(QtGui.QLineEdit.Password)
        self.admin_edit_old_password.setObjectName(_fromUtf8("admin_edit_old_password"))
        self.admin_edit_username = QtGui.QLineEdit(self.groupBox_5)
        self.admin_edit_username.setGeometry(QtCore.QRect(70, 30, 271, 41))
        self.admin_edit_username.setObjectName(_fromUtf8("admin_edit_username"))
        self.groupBox_6 = QtGui.QGroupBox(self.admin_tab)
        self.groupBox_6.setGeometry(QtCore.QRect(300, 250, 391, 251))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.admin_add_username = QtGui.QLineEdit(self.groupBox_6)
        self.admin_add_username.setGeometry(QtCore.QRect(60, 30, 271, 41))
        self.admin_add_username.setObjectName(_fromUtf8("admin_add_username"))
        self.admin_add_password = QtGui.QLineEdit(self.groupBox_6)
        self.admin_add_password.setGeometry(QtCore.QRect(60, 70, 271, 41))
        self.admin_add_password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.admin_add_password.setText(_fromUtf8(""))
        self.admin_add_password.setEchoMode(QtGui.QLineEdit.Password)
        self.admin_add_password.setObjectName(_fromUtf8("admin_add_password"))
        self.admin_add_btn = QtGui.QPushButton(self.groupBox_6)
        self.admin_add_btn.setGeometry(QtCore.QRect(60, 120, 111, 41))
        self.admin_add_btn.setAutoDefault(True)
        self.admin_add_btn.setObjectName(_fromUtf8("admin_add_btn"))
        self.admin_add_error = QtGui.QLabel(self.groupBox_6)
        self.admin_add_error.setGeometry(QtCore.QRect(180, 130, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.admin_add_error.setFont(font)
        self.admin_add_error.setStyleSheet(_fromUtf8("QLabel {\n"
"color:rgb(255, 0, 0);\n"
"}"))
        self.admin_add_error.setText(_fromUtf8(""))
        self.admin_add_error.setTextFormat(QtCore.Qt.RichText)
        self.admin_add_error.setObjectName(_fromUtf8("admin_add_error"))
        self.groupBox_7 = QtGui.QGroupBox(self.admin_tab)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 0, 251, 511))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.admins_table = QtGui.QTableWidget(self.groupBox_7)
        self.admins_table.setGeometry(QtCore.QRect(20, 130, 211, 371))
        self.admins_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.admins_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.admins_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.admins_table.setObjectName(_fromUtf8("admins_table"))
        self.admins_table.setColumnCount(2)
        self.admins_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.admins_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.admins_table.setHorizontalHeaderItem(1, item)
        self.admins_table.verticalHeader().setVisible(False)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 30, 311, 51))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.admin_search_id = QtGui.QLineEdit(self.groupBox_8)
        self.admin_search_id.setGeometry(QtCore.QRect(10, 20, 71, 32))
        self.admin_search_id.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.admin_search_id.setObjectName(_fromUtf8("admin_search_id"))
        self.admin_search_username = QtGui.QLineEdit(self.groupBox_8)
        self.admin_search_username.setGeometry(QtCore.QRect(80, 20, 141, 32))
        self.admin_search_username.setObjectName(_fromUtf8("admin_search_username"))
        self.admin_search_btn = QtGui.QPushButton(self.groupBox_7)
        self.admin_search_btn.setGeometry(QtCore.QRect(70, 90, 101, 31))
        self.admin_search_btn.setAutoDefault(True)
        self.admin_search_btn.setObjectName(_fromUtf8("admin_search_btn"))
        self.line_4 = QtGui.QFrame(self.admin_tab)
        self.line_4.setGeometry(QtCore.QRect(260, 0, 41, 511))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.admin_tab)
        self.line_5.setGeometry(QtCore.QRect(280, 230, 501, 21))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("img/admin.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_tabs.addTab(self.admin_tab, icon3, _fromUtf8(""))
        self.options_tab = QtGui.QWidget()
        self.options_tab.setObjectName(_fromUtf8("options_tab"))
        self.groupBox_11 = QtGui.QGroupBox(self.options_tab)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 0, 761, 131))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.db_backup_btn = QtGui.QPushButton(self.groupBox_11)
        self.db_backup_btn.setGeometry(QtCore.QRect(50, 40, 92, 28))
        self.db_backup_btn.setObjectName(_fromUtf8("db_backup_btn"))
        self.db_restore_btn = QtGui.QPushButton(self.groupBox_11)
        self.db_restore_btn.setGeometry(QtCore.QRect(150, 40, 92, 28))
        self.db_restore_btn.setObjectName(_fromUtf8("db_restore_btn"))
        self.db_error = QtGui.QLabel(self.groupBox_11)
        self.db_error.setGeometry(QtCore.QRect(50, 80, 701, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.db_error.setFont(font)
        self.db_error.setStyleSheet(_fromUtf8("QLabel {\n"
"color:rgb(255, 0, 0);\n"
"}"))
        self.db_error.setText(_fromUtf8(""))
        self.db_error.setTextFormat(QtCore.Qt.RichText)
        self.db_error.setObjectName(_fromUtf8("db_error"))
        self.groupBox_12 = QtGui.QGroupBox(self.options_tab)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 370, 751, 131))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.line_7 = QtGui.QFrame(self.options_tab)
        self.line_7.setGeometry(QtCore.QRect(0, 130, 781, 20))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.line_8 = QtGui.QFrame(self.options_tab)
        self.line_8.setGeometry(QtCore.QRect(0, 350, 781, 20))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("img/options.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_tabs.addTab(self.options_tab, icon4, _fromUtf8(""))
        self.log_viewer = QtGui.QPlainTextEdit(self.centralwidget)
        self.log_viewer.setGeometry(QtCore.QRect(0, 540, 791, 41))
        self.log_viewer.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.log_viewer.setReadOnly(True)
        self.log_viewer.setObjectName(_fromUtf8("log_viewer"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.main_tabs.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MeX LMS", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Add Book", None))
        self.book_add_btn.setText(_translate("MainWindow", "Add Book", None))
        self.book_add_copies.setPlaceholderText(_translate("MainWindow", "No. of copies", None))
        self.book_add_title.setPlaceholderText(_translate("MainWindow", "Title", None))
        self.book_add_author.setPlaceholderText(_translate("MainWindow", "Author", None))
        self.book_add_publisher.setPlaceholderText(_translate("MainWindow", "Publisher", None))
        self.book_add_available.setText(_translate("MainWindow", "Available", None))
        item = self.books_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.books_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title", None))
        item = self.books_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Available", None))
        item = self.books_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Copies", None))
        item = self.books_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Author", None))
        item = self.books_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Publisher", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Search", None))
        self.book_search_btn.setText(_translate("MainWindow", "Search", None))
        self.book_search_id.setPlaceholderText(_translate("MainWindow", "ID", None))
        self.book_search_title.setPlaceholderText(_translate("MainWindow", "Title", None))
        self.book_search_author.setPlaceholderText(_translate("MainWindow", "Author", None))
        self.book_search_publisher.setPlaceholderText(_translate("MainWindow", "Publisher", None))
        self.book_search_available.setText(_translate("MainWindow", "Available", None))
        self.book_search_not_available.setText(_translate("MainWindow", "Not Available", None))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.books_tab), _translate("MainWindow", "Books", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Add Member", None))
        self.member_add_btn.setText(_translate("MainWindow", "Add Member", None))
        self.member_add_name.setPlaceholderText(_translate("MainWindow", "Name", None))
        self.member_add_email.setPlaceholderText(_translate("MainWindow", "Email", None))
        self.member_add_mob.setPlaceholderText(_translate("MainWindow", "Mobile No.", None))
        self.groupBox.setTitle(_translate("MainWindow", "Search", None))
        self.member_search_id.setPlaceholderText(_translate("MainWindow", "ID", None))
        self.member_search_name.setPlaceholderText(_translate("MainWindow", "Name", None))
        self.member_search_email.setPlaceholderText(_translate("MainWindow", "Email", None))
        self.member_search_mob.setPlaceholderText(_translate("MainWindow", "Mobile No.", None))
        self.member_search_btn.setText(_translate("MainWindow", "Search", None))
        item = self.members_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.members_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.members_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "fine", None))
        item = self.members_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Email", None))
        item = self.members_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Mobile", None))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.members_tab), _translate("MainWindow", "Members", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Add Book", None))
        self.borrow_add_btn.setText(_translate("MainWindow", "Add Borrow", None))
        self.borrow_add_book_id.setPlaceholderText(_translate("MainWindow", "Book ID", None))
        self.borrow_add_member_id.setPlaceholderText(_translate("MainWindow", "Member ID", None))
        self.borrow_add_active.setText(_translate("MainWindow", "Active", None))
        self.label.setText(_translate("MainWindow", "Start", None))
        self.label_2.setText(_translate("MainWindow", "End", None))
        item = self.borrows_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.borrows_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Book ID", None))
        item = self.borrows_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Book Title", None))
        item = self.borrows_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Member ID", None))
        item = self.borrows_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Member Name", None))
        item = self.borrows_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Start", None))
        item = self.borrows_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "End", None))
        item = self.borrows_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Active", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Search", None))
        self.borrow_search_btn.setText(_translate("MainWindow", "Search", None))
        self.borrow_search_id.setPlaceholderText(_translate("MainWindow", "ID", None))
        self.borrow_search_active.setText(_translate("MainWindow", "Active", None))
        self.borrow_search_not_active.setText(_translate("MainWindow", "Not Active", None))
        self.borrow_search_book_id.setPlaceholderText(_translate("MainWindow", "Book ID", None))
        self.borrow_search_member_id.setPlaceholderText(_translate("MainWindow", "Member ID", None))
        self.label_3.setText(_translate("MainWindow", "Start", None))
        self.label_4.setText(_translate("MainWindow", "End", None))
        self.label_5.setText(_translate("MainWindow", "To", None))
        self.label_6.setText(_translate("MainWindow", "From", None))
        self.label_11.setText(_translate("MainWindow", "Time period:", None))
        self.borrow_search_member_name.setPlaceholderText(_translate("MainWindow", "Member Name", None))
        self.borrow_search_book_title.setPlaceholderText(_translate("MainWindow", "Book Name", None))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.borrows_tab), _translate("MainWindow", "Borrow", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Current Admin", None))
        self.admin_edit_btn.setText(_translate("MainWindow", "Update Info", None))
        self.admin_edit_new_password.setPlaceholderText(_translate("MainWindow", "new password", None))
        self.admin_edit_old_password.setPlaceholderText(_translate("MainWindow", "old password", None))
        self.admin_edit_username.setPlaceholderText(_translate("MainWindow", "username", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Add Admin", None))
        self.admin_add_username.setPlaceholderText(_translate("MainWindow", "username", None))
        self.admin_add_password.setPlaceholderText(_translate("MainWindow", "password", None))
        self.admin_add_btn.setText(_translate("MainWindow", "Add Admin", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Admins", None))
        item = self.admins_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.admins_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "username", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Search", None))
        self.admin_search_id.setPlaceholderText(_translate("MainWindow", "ID", None))
        self.admin_search_username.setPlaceholderText(_translate("MainWindow", "username", None))
        self.admin_search_btn.setText(_translate("MainWindow", "Search", None))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.admin_tab), _translate("MainWindow", "Admin", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "Database", None))
        self.db_backup_btn.setText(_translate("MainWindow", "Backup", None))
        self.db_restore_btn.setText(_translate("MainWindow", "Restore", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "About", None))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.options_tab), _translate("MainWindow", "Options", None))

