# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lmsgui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(788, 575)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.main_tabs = QtGui.QTabWidget(self.centralwidget)
        self.main_tabs.setGeometry(QtCore.QRect(0, 0, 781, 551))
        self.main_tabs.setObjectName(_fromUtf8("main_tabs"))
        self.books_tab = QtGui.QWidget()
        self.books_tab.setObjectName(_fromUtf8("books_tab"))
        self.scrollArea = QtGui.QScrollArea(self.books_tab)
        self.scrollArea.setGeometry(QtCore.QRect(0, 120, 771, 361))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 769, 359))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.books_table = QtGui.QTableWidget(self.scrollAreaWidgetContents)
        self.books_table.setGeometry(QtCore.QRect(20, 60, 731, 291))
        self.books_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.books_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.books_table.setObjectName(_fromUtf8("books_table"))
        self.books_table.setColumnCount(6)
        self.books_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.books_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.books_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.books_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.books_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.books_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.books_table.setHorizontalHeaderItem(5, item)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 761, 51))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.book_search_btn = QtGui.QPushButton(self.groupBox_2)
        self.book_search_btn.setGeometry(QtCore.QRect(670, 20, 81, 31))
        self.book_search_btn.setAutoDefault(True)
        self.book_search_btn.setObjectName(_fromUtf8("book_search_btn"))
        self.book_search_id = QtGui.QLineEdit(self.groupBox_2)
        self.book_search_id.setGeometry(QtCore.QRect(10, 20, 41, 32))
        self.book_search_id.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.book_search_id.setObjectName(_fromUtf8("book_search_id"))
        self.book_search_title = QtGui.QLineEdit(self.groupBox_2)
        self.book_search_title.setGeometry(QtCore.QRect(50, 20, 191, 32))
        self.book_search_title.setObjectName(_fromUtf8("book_search_title"))
        self.book_search_author = QtGui.QLineEdit(self.groupBox_2)
        self.book_search_author.setGeometry(QtCore.QRect(240, 20, 171, 32))
        self.book_search_author.setInputMethodHints(QtCore.Qt.ImhNone)
        self.book_search_author.setObjectName(_fromUtf8("book_search_author"))
        self.book_search_publisher = QtGui.QLineEdit(self.groupBox_2)
        self.book_search_publisher.setGeometry(QtCore.QRect(410, 20, 141, 32))
        self.book_search_publisher.setInputMethodHints(QtCore.Qt.ImhNone)
        self.book_search_publisher.setObjectName(_fromUtf8("book_search_publisher"))
        self.book_search_available = QtGui.QCheckBox(self.groupBox_2)
        self.book_search_available.setGeometry(QtCore.QRect(550, 10, 91, 25))
        self.book_search_available.setChecked(True)
        self.book_search_available.setObjectName(_fromUtf8("book_search_available"))
        self.book_search_not_available = QtGui.QCheckBox(self.groupBox_2)
        self.book_search_not_available.setGeometry(QtCore.QRect(550, 30, 111, 25))
        self.book_search_not_available.setChecked(True)
        self.book_search_not_available.setObjectName(_fromUtf8("book_search_not_available"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.groupBox_4 = QtGui.QGroupBox(self.books_tab)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 10, 751, 101))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.book_add_btn = QtGui.QPushButton(self.groupBox_4)
        self.book_add_btn.setGeometry(QtCore.QRect(610, 20, 101, 31))
        self.book_add_btn.setAutoDefault(True)
        self.book_add_btn.setObjectName(_fromUtf8("book_add_btn"))
        self.book_add_copies = QtGui.QLineEdit(self.groupBox_4)
        self.book_add_copies.setGeometry(QtCore.QRect(20, 60, 211, 32))
        self.book_add_copies.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.book_add_copies.setText(_fromUtf8(""))
        self.book_add_copies.setObjectName(_fromUtf8("book_add_copies"))
        self.book_add_title = QtGui.QLineEdit(self.groupBox_4)
        self.book_add_title.setGeometry(QtCore.QRect(20, 20, 211, 32))
        self.book_add_title.setObjectName(_fromUtf8("book_add_title"))
        self.book_add_author = QtGui.QLineEdit(self.groupBox_4)
        self.book_add_author.setGeometry(QtCore.QRect(240, 20, 201, 32))
        self.book_add_author.setInputMethodHints(QtCore.Qt.ImhNone)
        self.book_add_author.setObjectName(_fromUtf8("book_add_author"))
        self.book_add_publisher = QtGui.QLineEdit(self.groupBox_4)
        self.book_add_publisher.setGeometry(QtCore.QRect(450, 20, 151, 32))
        self.book_add_publisher.setInputMethodHints(QtCore.Qt.ImhNone)
        self.book_add_publisher.setObjectName(_fromUtf8("book_add_publisher"))
        self.book_add_error = QtGui.QLabel(self.groupBox_4)
        self.book_add_error.setGeometry(QtCore.QRect(520, 60, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.book_add_error.setFont(font)
        self.book_add_error.setStyleSheet(_fromUtf8("QLabel {\n"
"color:rgb(255, 0, 0);\n"
"}"))
        self.book_add_error.setText(_fromUtf8(""))
        self.book_add_error.setTextFormat(QtCore.Qt.RichText)
        self.book_add_error.setObjectName(_fromUtf8("book_add_error"))
        self.book_add_available = QtGui.QCheckBox(self.groupBox_4)
        self.book_add_available.setGeometry(QtCore.QRect(240, 60, 91, 25))
        self.book_add_available.setChecked(True)
        self.book_add_available.setObjectName(_fromUtf8("book_add_available"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/book.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_tabs.addTab(self.books_tab, icon, _fromUtf8(""))
        self.members_tab = QtGui.QWidget()
        self.members_tab.setObjectName(_fromUtf8("members_tab"))
        self.scrollArea_2 = QtGui.QScrollArea(self.members_tab)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 70, 771, 411))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 769, 409))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.members_table = QtGui.QTableWidget(self.scrollAreaWidgetContents_2)
        self.members_table.setGeometry(QtCore.QRect(20, 70, 731, 331))
        self.members_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.members_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.members_table.setObjectName(_fromUtf8("members_table"))
        self.members_table.setColumnCount(5)
        self.members_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(4, item)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 751, 51))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.member_search_btn = QtGui.QPushButton(self.groupBox)
        self.member_search_btn.setGeometry(QtCore.QRect(640, 20, 101, 31))
        self.member_search_btn.setAutoDefault(True)
        self.member_search_btn.setObjectName(_fromUtf8("member_search_btn"))
        self.member_search_id = QtGui.QLineEdit(self.groupBox)
        self.member_search_id.setGeometry(QtCore.QRect(10, 20, 61, 32))
        self.member_search_id.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.member_search_id.setObjectName(_fromUtf8("member_search_id"))
        self.member_search_name = QtGui.QLineEdit(self.groupBox)
        self.member_search_name.setGeometry(QtCore.QRect(70, 20, 211, 32))
        self.member_search_name.setObjectName(_fromUtf8("member_search_name"))
        self.member_search_email = QtGui.QLineEdit(self.groupBox)
        self.member_search_email.setGeometry(QtCore.QRect(280, 20, 201, 32))
        self.member_search_email.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.member_search_email.setObjectName(_fromUtf8("member_search_email"))
        self.member_search_mob = QtGui.QLineEdit(self.groupBox)
        self.member_search_mob.setGeometry(QtCore.QRect(480, 20, 151, 32))
        self.member_search_mob.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.member_search_mob.setObjectName(_fromUtf8("member_search_mob"))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.groupBox_9 = QtGui.QGroupBox(self.members_tab)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 0, 771, 61))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.member_add_btn = QtGui.QPushButton(self.groupBox_9)
        self.member_add_btn.setGeometry(QtCore.QRect(470, 20, 101, 31))
        self.member_add_btn.setAutoDefault(True)
        self.member_add_btn.setObjectName(_fromUtf8("member_add_btn"))
        self.member_add_name = QtGui.QLineEdit(self.groupBox_9)
        self.member_add_name.setGeometry(QtCore.QRect(20, 20, 161, 32))
        self.member_add_name.setObjectName(_fromUtf8("member_add_name"))
        self.member_add_email = QtGui.QLineEdit(self.groupBox_9)
        self.member_add_email.setGeometry(QtCore.QRect(180, 20, 161, 32))
        self.member_add_email.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.member_add_email.setObjectName(_fromUtf8("member_add_email"))
        self.member_add_mob = QtGui.QLineEdit(self.groupBox_9)
        self.member_add_mob.setGeometry(QtCore.QRect(340, 20, 121, 32))
        self.member_add_mob.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.member_add_mob.setObjectName(_fromUtf8("member_add_mob"))
        self.member_add_error = QtGui.QLabel(self.groupBox_9)
        self.member_add_error.setGeometry(QtCore.QRect(580, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.member_add_error.setFont(font)
        self.member_add_error.setStyleSheet(_fromUtf8("QLabel {\n"
"color:rgb(255, 0, 0);\n"
"}"))
        self.member_add_error.setText(_fromUtf8(""))
        self.member_add_error.setTextFormat(QtCore.Qt.RichText)
        self.member_add_error.setObjectName(_fromUtf8("member_add_error"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/member.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_tabs.addTab(self.members_tab, icon1, _fromUtf8(""))
        self.admin_tab = QtGui.QWidget()
        self.admin_tab.setObjectName(_fromUtf8("admin_tab"))
        self.groupBox_5 = QtGui.QGroupBox(self.admin_tab)
        self.groupBox_5.setGeometry(QtCore.QRect(380, 0, 381, 221))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.admin_edit_btn = QtGui.QPushButton(self.groupBox_5)
        self.admin_edit_btn.setGeometry(QtCore.QRect(70, 160, 111, 41))
        self.admin_edit_btn.setAutoDefault(True)
        self.admin_edit_btn.setObjectName(_fromUtf8("admin_edit_btn"))
        self.admin_edit_error = QtGui.QLabel(self.groupBox_5)
        self.admin_edit_error.setGeometry(QtCore.QRect(180, 160, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.admin_edit_error.setFont(font)
        self.admin_edit_error.setStyleSheet(_fromUtf8("QLabel {\n"
"color:rgb(255, 0, 0);\n"
"}"))
        self.admin_edit_error.setText(_fromUtf8(""))
        self.admin_edit_error.setTextFormat(QtCore.Qt.RichText)
        self.admin_edit_error.setObjectName(_fromUtf8("admin_edit_error"))
        self.admin_edit_new_password = QtGui.QLineEdit(self.groupBox_5)
        self.admin_edit_new_password.setGeometry(QtCore.QRect(70, 110, 271, 41))
        self.admin_edit_new_password.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.admin_edit_new_password.setText(_fromUtf8(""))
        self.admin_edit_new_password.setObjectName(_fromUtf8("admin_edit_new_password"))
        self.admin_edit_old_password = QtGui.QLineEdit(self.groupBox_5)
        self.admin_edit_old_password.setGeometry(QtCore.QRect(70, 70, 271, 41))
        self.admin_edit_old_password.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.admin_edit_old_password.setText(_fromUtf8(""))
        self.admin_edit_old_password.setObjectName(_fromUtf8("admin_edit_old_password"))
        self.admin_edit_username = QtGui.QLineEdit(self.groupBox_5)
        self.admin_edit_username.setGeometry(QtCore.QRect(70, 30, 271, 41))
        self.admin_edit_username.setObjectName(_fromUtf8("admin_edit_username"))
        self.groupBox_6 = QtGui.QGroupBox(self.admin_tab)
        self.groupBox_6.setGeometry(QtCore.QRect(400, 260, 371, 171))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.admin_add_username = QtGui.QLineEdit(self.groupBox_6)
        self.admin_add_username.setGeometry(QtCore.QRect(60, 30, 271, 41))
        self.admin_add_username.setObjectName(_fromUtf8("admin_add_username"))
        self.admin_add_password = QtGui.QLineEdit(self.groupBox_6)
        self.admin_add_password.setGeometry(QtCore.QRect(60, 70, 271, 41))
        self.admin_add_password.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.admin_add_password.setText(_fromUtf8(""))
        self.admin_add_password.setObjectName(_fromUtf8("admin_add_password"))
        self.admin_add_btn = QtGui.QPushButton(self.groupBox_6)
        self.admin_add_btn.setGeometry(QtCore.QRect(60, 120, 111, 41))
        self.admin_add_btn.setAutoDefault(True)
        self.admin_add_btn.setObjectName(_fromUtf8("admin_add_btn"))
        self.admin_add_error = QtGui.QLabel(self.groupBox_6)
        self.admin_add_error.setGeometry(QtCore.QRect(180, 130, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.admin_add_error.setFont(font)
        self.admin_add_error.setStyleSheet(_fromUtf8("QLabel {\n"
"color:rgb(255, 0, 0);\n"
"}"))
        self.admin_add_error.setText(_fromUtf8(""))
        self.admin_add_error.setTextFormat(QtCore.Qt.RichText)
        self.admin_add_error.setObjectName(_fromUtf8("admin_add_error"))
        self.groupBox_7 = QtGui.QGroupBox(self.admin_tab)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 321, 481))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.admins_table = QtGui.QTableWidget(self.groupBox_7)
        self.admins_table.setGeometry(QtCore.QRect(20, 90, 281, 391))
        self.admins_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.admins_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.admins_table.setObjectName(_fromUtf8("admins_table"))
        self.admins_table.setColumnCount(2)
        self.admins_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.admins_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.admins_table.setHorizontalHeaderItem(1, item)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 30, 311, 51))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.admin_search_btn = QtGui.QPushButton(self.groupBox_8)
        self.admin_search_btn.setGeometry(QtCore.QRect(200, 20, 101, 31))
        self.admin_search_btn.setAutoDefault(True)
        self.admin_search_btn.setObjectName(_fromUtf8("admin_search_btn"))
        self.admin_search_id = QtGui.QLineEdit(self.groupBox_8)
        self.admin_search_id.setGeometry(QtCore.QRect(10, 20, 51, 32))
        self.admin_search_id.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.admin_search_id.setObjectName(_fromUtf8("admin_search_id"))
        self.admin_search_username = QtGui.QLineEdit(self.groupBox_8)
        self.admin_search_username.setGeometry(QtCore.QRect(60, 20, 141, 32))
        self.admin_search_username.setObjectName(_fromUtf8("admin_search_username"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("img/admin.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_tabs.addTab(self.admin_tab, icon2, _fromUtf8(""))
        self.options_tab = QtGui.QWidget()
        self.options_tab.setObjectName(_fromUtf8("options_tab"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("img/options.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_tabs.addTab(self.options_tab, icon3, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionAdd_Book = QtGui.QAction(MainWindow)
        self.actionAdd_Book.setObjectName(_fromUtf8("actionAdd_Book"))
        self.actionView_books = QtGui.QAction(MainWindow)
        self.actionView_books.setObjectName(_fromUtf8("actionView_books"))
        self.actionView_members = QtGui.QAction(MainWindow)
        self.actionView_members.setObjectName(_fromUtf8("actionView_members"))
        self.actionAdd_member = QtGui.QAction(MainWindow)
        self.actionAdd_member.setObjectName(_fromUtf8("actionAdd_member"))
        self.actionAdd_admin = QtGui.QAction(MainWindow)
        self.actionAdd_admin.setObjectName(_fromUtf8("actionAdd_admin"))
        self.actionChange_password = QtGui.QAction(MainWindow)
        self.actionChange_password.setObjectName(_fromUtf8("actionChange_password"))

        self.retranslateUi(MainWindow)
        self.main_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MeX LMS", None))
        item = self.books_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.books_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title", None))
        item = self.books_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Available", None))
        item = self.books_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Copies", None))
        item = self.books_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Author", None))
        item = self.books_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Publisher", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Search", None))
        self.book_search_btn.setText(_translate("MainWindow", "Search", None))
        self.book_search_id.setPlaceholderText(_translate("MainWindow", "ID", None))
        self.book_search_title.setPlaceholderText(_translate("MainWindow", "Title", None))
        self.book_search_author.setPlaceholderText(_translate("MainWindow", "Author", None))
        self.book_search_publisher.setPlaceholderText(_translate("MainWindow", "Publisher", None))
        self.book_search_available.setText(_translate("MainWindow", "Available", None))
        self.book_search_not_available.setText(_translate("MainWindow", "Not Available", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Add Book", None))
        self.book_add_btn.setText(_translate("MainWindow", "Add Book", None))
        self.book_add_copies.setPlaceholderText(_translate("MainWindow", "No. of copies", None))
        self.book_add_title.setPlaceholderText(_translate("MainWindow", "Title", None))
        self.book_add_author.setPlaceholderText(_translate("MainWindow", "Author", None))
        self.book_add_publisher.setPlaceholderText(_translate("MainWindow", "Publisher", None))
        self.book_add_available.setText(_translate("MainWindow", "Available", None))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.books_tab), _translate("MainWindow", "Books", None))
        item = self.members_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.members_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.members_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "fine", None))
        item = self.members_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Email", None))
        item = self.members_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Mobile", None))
        self.groupBox.setTitle(_translate("MainWindow", "Search", None))
        self.member_search_btn.setText(_translate("MainWindow", "Search", None))
        self.member_search_id.setPlaceholderText(_translate("MainWindow", "ID", None))
        self.member_search_name.setPlaceholderText(_translate("MainWindow", "Name", None))
        self.member_search_email.setPlaceholderText(_translate("MainWindow", "Email", None))
        self.member_search_mob.setPlaceholderText(_translate("MainWindow", "Mobile No.", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Add Member", None))
        self.member_add_btn.setText(_translate("MainWindow", "Add Member", None))
        self.member_add_name.setPlaceholderText(_translate("MainWindow", "Name", None))
        self.member_add_email.setPlaceholderText(_translate("MainWindow", "Email", None))
        self.member_add_mob.setPlaceholderText(_translate("MainWindow", "Mobile No.", None))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.members_tab), _translate("MainWindow", "Members", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Current Admin", None))
        self.admin_edit_btn.setText(_translate("MainWindow", "Update Info", None))
        self.admin_edit_new_password.setPlaceholderText(_translate("MainWindow", "new password", None))
        self.admin_edit_old_password.setPlaceholderText(_translate("MainWindow", "old password", None))
        self.admin_edit_username.setPlaceholderText(_translate("MainWindow", "username", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Add Admin", None))
        self.admin_add_username.setPlaceholderText(_translate("MainWindow", "username", None))
        self.admin_add_password.setPlaceholderText(_translate("MainWindow", "password", None))
        self.admin_add_btn.setText(_translate("MainWindow", "Add Admin", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Admins", None))
        item = self.admins_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.admins_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "username", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Search", None))
        self.admin_search_btn.setText(_translate("MainWindow", "Search", None))
        self.admin_search_id.setPlaceholderText(_translate("MainWindow", "ID", None))
        self.admin_search_username.setPlaceholderText(_translate("MainWindow", "username", None))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.admin_tab), _translate("MainWindow", "Admin", None))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.options_tab), _translate("MainWindow", "Options", None))
        self.actionImport.setText(_translate("MainWindow", "import", None))
        self.actionExport.setText(_translate("MainWindow", "export", None))
        self.actionAdd_Book.setText(_translate("MainWindow", "Add Book", None))
        self.actionView_books.setText(_translate("MainWindow", "View books", None))
        self.actionView_members.setText(_translate("MainWindow", "View members", None))
        self.actionAdd_member.setText(_translate("MainWindow", "Add member", None))
        self.actionAdd_admin.setText(_translate("MainWindow", "Add admin", None))
        self.actionChange_password.setText(_translate("MainWindow", "Change password", None))

