# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lmsmemberedit.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MemberEdit(object):
    def setupUi(self, MemberEdit):
        MemberEdit.setObjectName(_fromUtf8("MemberEdit"))
        MemberEdit.resize(509, 357)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MemberEdit.setWindowIcon(icon)
        MemberEdit.setStyleSheet(_fromUtf8(""))
        self.member_edit_name = QtGui.QLineEdit(MemberEdit)
        self.member_edit_name.setGeometry(QtCore.QRect(150, 100, 221, 32))
        self.member_edit_name.setObjectName(_fromUtf8("member_edit_name"))
        self.member_edit_mob = QtGui.QLineEdit(MemberEdit)
        self.member_edit_mob.setGeometry(QtCore.QRect(150, 180, 221, 32))
        self.member_edit_mob.setInputMethodHints(QtCore.Qt.ImhNone)
        self.member_edit_mob.setObjectName(_fromUtf8("member_edit_mob"))
        self.member_edit_email = QtGui.QLineEdit(MemberEdit)
        self.member_edit_email.setGeometry(QtCore.QRect(150, 140, 221, 32))
        self.member_edit_email.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.member_edit_email.setObjectName(_fromUtf8("member_edit_email"))
        self.member_edit_fine = QtGui.QLineEdit(MemberEdit)
        self.member_edit_fine.setGeometry(QtCore.QRect(150, 220, 221, 32))
        self.member_edit_fine.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.member_edit_fine.setText(_fromUtf8(""))
        self.member_edit_fine.setObjectName(_fromUtf8("member_edit_fine"))
        self.label_2 = QtGui.QLabel(MemberEdit)
        self.label_2.setGeometry(QtCore.QRect(90, 100, 51, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtGui.QFrame.Plain)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(MemberEdit)
        self.label_3.setGeometry(QtCore.QRect(90, 140, 61, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtGui.QFrame.Plain)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(MemberEdit)
        self.label_4.setGeometry(QtCore.QRect(70, 180, 71, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_4.setFrameShadow(QtGui.QFrame.Plain)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(MemberEdit)
        self.label_5.setGeometry(QtCore.QRect(100, 220, 41, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_5.setFrameShadow(QtGui.QFrame.Plain)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(MemberEdit)
        self.label_6.setGeometry(QtCore.QRect(170, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_6.setFrameShadow(QtGui.QFrame.Plain)
        self.label_6.setLineWidth(1)
        self.label_6.setMidLineWidth(0)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.member_edit_btn = QtGui.QPushButton(MemberEdit)
        self.member_edit_btn.setGeometry(QtCore.QRect(310, 310, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.member_edit_btn.setFont(font)
        self.member_edit_btn.setAutoDefault(True)
        self.member_edit_btn.setFlat(False)
        self.member_edit_btn.setObjectName(_fromUtf8("member_edit_btn"))
        self.member_edit_cancel_btn = QtGui.QPushButton(MemberEdit)
        self.member_edit_cancel_btn.setGeometry(QtCore.QRect(210, 310, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.member_edit_cancel_btn.setFont(font)
        self.member_edit_cancel_btn.setAutoDefault(True)
        self.member_edit_cancel_btn.setObjectName(_fromUtf8("member_edit_cancel_btn"))
        self.member_delete_btn = QtGui.QPushButton(MemberEdit)
        self.member_delete_btn.setGeometry(QtCore.QRect(110, 310, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.member_delete_btn.setFont(font)
        self.member_delete_btn.setCheckable(False)
        self.member_delete_btn.setAutoDefault(True)
        self.member_delete_btn.setObjectName(_fromUtf8("member_delete_btn"))
        self.member_edit_error = QtGui.QLabel(MemberEdit)
        self.member_edit_error.setGeometry(QtCore.QRect(140, 260, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.member_edit_error.setFont(font)
        self.member_edit_error.setText(_fromUtf8(""))
        self.member_edit_error.setObjectName(_fromUtf8("member_edit_error"))
        self.member_edit_id = QtGui.QLineEdit(MemberEdit)
        self.member_edit_id.setGeometry(QtCore.QRect(150, 60, 221, 32))
        self.member_edit_id.setReadOnly(True)
        self.member_edit_id.setObjectName(_fromUtf8("member_edit_id"))
        self.label = QtGui.QLabel(MemberEdit)
        self.label.setGeometry(QtCore.QRect(100, 60, 31, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setFrameShadow(QtGui.QFrame.Plain)
        self.label.setObjectName(_fromUtf8("label"))

        self.retranslateUi(MemberEdit)
        QtCore.QMetaObject.connectSlotsByName(MemberEdit)

    def retranslateUi(self, MemberEdit):
        MemberEdit.setWindowTitle(_translate("MemberEdit", "MeX LMS - Edit Member", None))
        self.member_edit_name.setPlaceholderText(_translate("MemberEdit", "Name", None))
        self.member_edit_mob.setPlaceholderText(_translate("MemberEdit", "Mobile number", None))
        self.member_edit_email.setPlaceholderText(_translate("MemberEdit", "Email", None))
        self.member_edit_fine.setPlaceholderText(_translate("MemberEdit", "Fine", None))
        self.label_2.setText(_translate("MemberEdit", "Name", None))
        self.label_3.setText(_translate("MemberEdit", "Email", None))
        self.label_4.setText(_translate("MemberEdit", "Mob no.", None))
        self.label_5.setText(_translate("MemberEdit", "Fine", None))
        self.label_6.setText(_translate("MemberEdit", "Edit Member", None))
        self.member_edit_btn.setText(_translate("MemberEdit", "Save", None))
        self.member_edit_cancel_btn.setText(_translate("MemberEdit", "Close", None))
        self.member_delete_btn.setText(_translate("MemberEdit", "Delete", None))
        self.member_edit_id.setPlaceholderText(_translate("MemberEdit", "ID", None))
        self.label.setText(_translate("MemberEdit", "ID", None))

