# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maingui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(995, 590)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/img/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.nav_list = QtGui.QListWidget(self.centralwidget)
        self.nav_list.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.nav_list.setObjectName(_fromUtf8("nav_list"))
        item = QtGui.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/img/home.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.nav_list.addItem(item)
        item = QtGui.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/img/member.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.nav_list.addItem(item)
        item = QtGui.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/img/book.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.nav_list.addItem(item)
        item = QtGui.QListWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/img/borrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.nav_list.addItem(item)
        item = QtGui.QListWidgetItem()
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/img/options.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon5)
        self.nav_list.addItem(item)
        self.horizontalLayout_9.addWidget(self.nav_list)
        self.main_tabs = QtGui.QStackedWidget(self.centralwidget)
        self.main_tabs.setObjectName(_fromUtf8("main_tabs"))
        self.home_tab = QtGui.QWidget()
        self.home_tab.setObjectName(_fromUtf8("home_tab"))
        self.gridLayout_9 = QtGui.QGridLayout(self.home_tab)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.home_tab)
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.gridLayout_9.addWidget(self.textBrowser_2, 0, 0, 1, 1)
        self.main_tabs.addWidget(self.home_tab)
        self.members_tab = QtGui.QWidget()
        self.members_tab.setObjectName(_fromUtf8("members_tab"))
        self.gridLayout_12 = QtGui.QGridLayout(self.members_tab)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.members_tabs = QtGui.QTabWidget(self.members_tab)
        self.members_tabs.setObjectName(_fromUtf8("members_tabs"))
        self.members_browse_tab = QtGui.QWidget()
        self.members_browse_tab.setObjectName(_fromUtf8("members_browse_tab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.members_browse_tab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox = QtGui.QGroupBox(self.members_browse_tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.member_search_id = QtGui.QLineEdit(self.groupBox)
        self.member_search_id.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.member_search_id.setObjectName(_fromUtf8("member_search_id"))
        self.horizontalLayout_10.addWidget(self.member_search_id)
        self.member_search_name = QtGui.QLineEdit(self.groupBox)
        self.member_search_name.setObjectName(_fromUtf8("member_search_name"))
        self.horizontalLayout_10.addWidget(self.member_search_name)
        self.member_search_email = QtGui.QLineEdit(self.groupBox)
        self.member_search_email.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.member_search_email.setObjectName(_fromUtf8("member_search_email"))
        self.horizontalLayout_10.addWidget(self.member_search_email)
        self.member_search_mob = QtGui.QLineEdit(self.groupBox)
        self.member_search_mob.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.member_search_mob.setObjectName(_fromUtf8("member_search_mob"))
        self.horizontalLayout_10.addWidget(self.member_search_mob)
        self.member_search_btn = QtGui.QPushButton(self.groupBox)
        self.member_search_btn.setAutoDefault(True)
        self.member_search_btn.setObjectName(_fromUtf8("member_search_btn"))
        self.horizontalLayout_10.addWidget(self.member_search_btn)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 2)
        self.horizontalLayout_10.setStretch(2, 2)
        self.horizontalLayout_10.setStretch(3, 2)
        self.horizontalLayout_10.setStretch(4, 2)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.members_table = QtGui.QTableWidget(self.members_browse_tab)
        self.members_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.members_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.members_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.members_table.setObjectName(_fromUtf8("members_table"))
        self.members_table.setColumnCount(6)
        self.members_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(5, item)
        self.verticalLayout_6.addWidget(self.members_table)
        self.members_tabs.addTab(self.members_browse_tab, _fromUtf8(""))
        self.members_add_tab = QtGui.QWidget()
        self.members_add_tab.setObjectName(_fromUtf8("members_add_tab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.members_add_tab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox_10 = QtGui.QGroupBox(self.members_add_tab)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.member_add_name = QtGui.QLineEdit(self.groupBox_10)
        self.member_add_name.setObjectName(_fromUtf8("member_add_name"))
        self.verticalLayout_12.addWidget(self.member_add_name)
        self.member_add_email = QtGui.QLineEdit(self.groupBox_10)
        self.member_add_email.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.member_add_email.setObjectName(_fromUtf8("member_add_email"))
        self.verticalLayout_12.addWidget(self.member_add_email)
        self.member_add_mob = QtGui.QLineEdit(self.groupBox_10)
        self.member_add_mob.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.member_add_mob.setObjectName(_fromUtf8("member_add_mob"))
        self.verticalLayout_12.addWidget(self.member_add_mob)
        self.member_add_note = QtGui.QPlainTextEdit(self.groupBox_10)
        self.member_add_note.setPlainText(_fromUtf8(""))
        self.member_add_note.setObjectName(_fromUtf8("member_add_note"))
        self.verticalLayout_12.addWidget(self.member_add_note)
        self.member_add_error = QtGui.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.member_add_error.setFont(font)
        self.member_add_error.setStyleSheet(_fromUtf8("QLabel {\n"
"color:rgb(255, 0, 0);\n"
"}"))
        self.member_add_error.setText(_fromUtf8(""))
        self.member_add_error.setTextFormat(QtCore.Qt.RichText)
        self.member_add_error.setAlignment(QtCore.Qt.AlignCenter)
        self.member_add_error.setWordWrap(True)
        self.member_add_error.setObjectName(_fromUtf8("member_add_error"))
        self.verticalLayout_12.addWidget(self.member_add_error)
        self.member_add_btn = QtGui.QPushButton(self.groupBox_10)
        self.member_add_btn.setAutoDefault(True)
        self.member_add_btn.setObjectName(_fromUtf8("member_add_btn"))
        self.verticalLayout_12.addWidget(self.member_add_btn)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 1)
        self.verticalLayout_12.setStretch(2, 1)
        self.verticalLayout_12.setStretch(3, 4)
        self.verticalLayout_12.setStretch(4, 2)
        self.verticalLayout_12.setStretch(5, 1)
        self.gridLayout_5.addWidget(self.groupBox_10, 0, 0, 1, 1)
        self.members_tabs.addTab(self.members_add_tab, _fromUtf8(""))
        self.gridLayout_12.addWidget(self.members_tabs, 0, 0, 1, 1)
        self.main_tabs.addWidget(self.members_tab)
        self.books_tab = QtGui.QWidget()
        self.books_tab.setObjectName(_fromUtf8("books_tab"))
        self.gridLayout_11 = QtGui.QGridLayout(self.books_tab)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.books_tabs = QtGui.QTabWidget(self.books_tab)
        self.books_tabs.setObjectName(_fromUtf8("books_tabs"))
        self.books_browse_tab = QtGui.QWidget()
        self.books_browse_tab.setObjectName(_fromUtf8("books_browse_tab"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.books_browse_tab)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.groupBox_2 = QtGui.QGroupBox(self.books_browse_tab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.book_search_id = QtGui.QLineEdit(self.groupBox_2)
        self.book_search_id.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.book_search_id.setObjectName(_fromUtf8("book_search_id"))
        self.horizontalLayout_12.addWidget(self.book_search_id)
        self.book_search_title = QtGui.QLineEdit(self.groupBox_2)
        self.book_search_title.setObjectName(_fromUtf8("book_search_title"))
        self.horizontalLayout_12.addWidget(self.book_search_title)
        self.book_search_author = QtGui.QLineEdit(self.groupBox_2)
        self.book_search_author.setInputMethodHints(QtCore.Qt.ImhNone)
        self.book_search_author.setObjectName(_fromUtf8("book_search_author"))
        self.horizontalLayout_12.addWidget(self.book_search_author)
        self.book_search_available = QtGui.QCheckBox(self.groupBox_2)
        self.book_search_available.setChecked(True)
        self.book_search_available.setObjectName(_fromUtf8("book_search_available"))
        self.horizontalLayout_12.addWidget(self.book_search_available)
        self.book_search_not_available = QtGui.QCheckBox(self.groupBox_2)
        self.book_search_not_available.setChecked(True)
        self.book_search_not_available.setObjectName(_fromUtf8("book_search_not_available"))
        self.horizontalLayout_12.addWidget(self.book_search_not_available)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 3)
        self.horizontalLayout_12.setStretch(2, 3)
        self.horizontalLayout_12.setStretch(3, 2)
        self.horizontalLayout_12.setStretch(4, 2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_28.addWidget(self.label_15)
        self.book_search_cat_id = QtGui.QLineEdit(self.groupBox_2)
        self.book_search_cat_id.setInputMethodHints(QtCore.Qt.ImhNone)
        self.book_search_cat_id.setReadOnly(False)
        self.book_search_cat_id.setObjectName(_fromUtf8("book_search_cat_id"))
        self.horizontalLayout_28.addWidget(self.book_search_cat_id)
        self.book_search_cat_name = QtGui.QComboBox(self.groupBox_2)
        self.book_search_cat_name.setObjectName(_fromUtf8("book_search_cat_name"))
        self.horizontalLayout_28.addWidget(self.book_search_cat_name)
        self.book_search_cat_custom_id = QtGui.QLineEdit(self.groupBox_2)
        self.book_search_cat_custom_id.setInputMethodHints(QtCore.Qt.ImhNone)
        self.book_search_cat_custom_id.setReadOnly(False)
        self.book_search_cat_custom_id.setObjectName(_fromUtf8("book_search_cat_custom_id"))
        self.horizontalLayout_28.addWidget(self.book_search_cat_custom_id)
        self.book_search_cat_order = QtGui.QLineEdit(self.groupBox_2)
        self.book_search_cat_order.setInputMethodHints(QtCore.Qt.ImhNone)
        self.book_search_cat_order.setObjectName(_fromUtf8("book_search_cat_order"))
        self.horizontalLayout_28.addWidget(self.book_search_cat_order)
        self.horizontalLayout_28.setStretch(0, 1)
        self.horizontalLayout_28.setStretch(1, 1)
        self.horizontalLayout_28.setStretch(2, 3)
        self.horizontalLayout_28.setStretch(3, 2)
        self.horizontalLayout_28.setStretch(4, 2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29.addLayout(self.verticalLayout_14)
        self.book_search_btn = QtGui.QPushButton(self.groupBox_2)
        self.book_search_btn.setAutoDefault(True)
        self.book_search_btn.setObjectName(_fromUtf8("book_search_btn"))
        self.horizontalLayout_29.addWidget(self.book_search_btn)
        self.verticalLayout_15.addWidget(self.groupBox_2)
        self.books_table = QtGui.QTableWidget(self.books_browse_tab)
        self.books_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.books_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.books_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.books_table.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.books_table.setObjectName(_fromUtf8("books_table"))
        self.books_table.setColumnCount(7)
        self.books_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.books_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.books_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.books_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.books_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.books_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.books_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.books_table.setHorizontalHeaderItem(6, item)
        self.verticalLayout_15.addWidget(self.books_table)
        self.books_tabs.addTab(self.books_browse_tab, _fromUtf8(""))
        self.Books_add_tab = QtGui.QWidget()
        self.Books_add_tab.setObjectName(_fromUtf8("Books_add_tab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.Books_add_tab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groupBox_4 = QtGui.QGroupBox(self.Books_add_tab)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.book_add_title = QtGui.QLineEdit(self.groupBox_4)
        self.book_add_title.setObjectName(_fromUtf8("book_add_title"))
        self.verticalLayout_13.addWidget(self.book_add_title)
        self.book_add_author = QtGui.QLineEdit(self.groupBox_4)
        self.book_add_author.setInputMethodHints(QtCore.Qt.ImhNone)
        self.book_add_author.setObjectName(_fromUtf8("book_add_author"))
        self.verticalLayout_13.addWidget(self.book_add_author)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_26.addWidget(self.label_9)
        self.book_add_cat_id = QtGui.QLineEdit(self.groupBox_4)
        self.book_add_cat_id.setInputMethodHints(QtCore.Qt.ImhNone)
        self.book_add_cat_id.setReadOnly(True)
        self.book_add_cat_id.setObjectName(_fromUtf8("book_add_cat_id"))
        self.horizontalLayout_26.addWidget(self.book_add_cat_id)
        self.book_add_cat_name = QtGui.QComboBox(self.groupBox_4)
        self.book_add_cat_name.setObjectName(_fromUtf8("book_add_cat_name"))
        self.horizontalLayout_26.addWidget(self.book_add_cat_name)
        self.book_add_cat_custom_id = QtGui.QLineEdit(self.groupBox_4)
        self.book_add_cat_custom_id.setInputMethodHints(QtCore.Qt.ImhNone)
        self.book_add_cat_custom_id.setReadOnly(True)
        self.book_add_cat_custom_id.setObjectName(_fromUtf8("book_add_cat_custom_id"))
        self.horizontalLayout_26.addWidget(self.book_add_cat_custom_id)
        self.book_add_cat_order = QtGui.QLineEdit(self.groupBox_4)
        self.book_add_cat_order.setInputMethodHints(QtCore.Qt.ImhNone)
        self.book_add_cat_order.setObjectName(_fromUtf8("book_add_cat_order"))
        self.horizontalLayout_26.addWidget(self.book_add_cat_order)
        self.horizontalLayout_26.setStretch(0, 1)
        self.horizontalLayout_26.setStretch(1, 1)
        self.horizontalLayout_26.setStretch(2, 3)
        self.horizontalLayout_26.setStretch(3, 2)
        self.horizontalLayout_26.setStretch(4, 2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_27.addWidget(self.label_10)
        self.book_add_state = QtGui.QPlainTextEdit(self.groupBox_4)
        self.book_add_state.setObjectName(_fromUtf8("book_add_state"))
        self.horizontalLayout_27.addWidget(self.book_add_state)
        self.verticalLayout_13.addLayout(self.horizontalLayout_27)
        self.book_add_copies = QtGui.QLineEdit(self.groupBox_4)
        self.book_add_copies.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.book_add_copies.setText(_fromUtf8(""))
        self.book_add_copies.setObjectName(_fromUtf8("book_add_copies"))
        self.verticalLayout_13.addWidget(self.book_add_copies)
        self.book_add_available = QtGui.QCheckBox(self.groupBox_4)
        self.book_add_available.setChecked(True)
        self.book_add_available.setObjectName(_fromUtf8("book_add_available"))
        self.verticalLayout_13.addWidget(self.book_add_available)
        self.book_add_error = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.book_add_error.setFont(font)
        self.book_add_error.setStyleSheet(_fromUtf8("QLabel {\n"
"color:rgb(255, 0, 0);\n"
"}"))
        self.book_add_error.setText(_fromUtf8(""))
        self.book_add_error.setTextFormat(QtCore.Qt.RichText)
        self.book_add_error.setAlignment(QtCore.Qt.AlignCenter)
        self.book_add_error.setWordWrap(True)
        self.book_add_error.setObjectName(_fromUtf8("book_add_error"))
        self.verticalLayout_13.addWidget(self.book_add_error)
        self.book_add_btn = QtGui.QPushButton(self.groupBox_4)
        self.book_add_btn.setAutoDefault(True)
        self.book_add_btn.setObjectName(_fromUtf8("book_add_btn"))
        self.verticalLayout_13.addWidget(self.book_add_btn)
        self.verticalLayout_13.setStretch(0, 1)
        self.verticalLayout_13.setStretch(1, 1)
        self.verticalLayout_13.setStretch(2, 1)
        self.verticalLayout_13.setStretch(3, 2)
        self.verticalLayout_13.setStretch(4, 1)
        self.verticalLayout_13.setStretch(5, 1)
        self.verticalLayout_13.setStretch(6, 3)
        self.verticalLayout_13.setStretch(7, 1)
        self.gridLayout_6.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.books_tabs.addTab(self.Books_add_tab, _fromUtf8(""))
        self.cats_tab = QtGui.QWidget()
        self.cats_tab.setObjectName(_fromUtf8("cats_tab"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.cats_tab)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.cats_table = QtGui.QTableWidget(self.cats_tab)
        self.cats_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.cats_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.cats_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.cats_table.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.cats_table.setObjectName(_fromUtf8("cats_table"))
        self.cats_table.setColumnCount(3)
        self.cats_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.cats_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.cats_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.cats_table.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_25.addWidget(self.cats_table)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.groupBox_8 = QtGui.QGroupBox(self.cats_tab)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.cat_search_id = QtGui.QLineEdit(self.groupBox_8)
        self.cat_search_id.setObjectName(_fromUtf8("cat_search_id"))
        self.verticalLayout_21.addWidget(self.cat_search_id)
        self.cat_search_name = QtGui.QLineEdit(self.groupBox_8)
        self.cat_search_name.setObjectName(_fromUtf8("cat_search_name"))
        self.verticalLayout_21.addWidget(self.cat_search_name)
        self.cat_search_custom_id = QtGui.QLineEdit(self.groupBox_8)
        self.cat_search_custom_id.setObjectName(_fromUtf8("cat_search_custom_id"))
        self.verticalLayout_21.addWidget(self.cat_search_custom_id)
        self.cat_search_btn = QtGui.QPushButton(self.groupBox_8)
        self.cat_search_btn.setAutoDefault(True)
        self.cat_search_btn.setObjectName(_fromUtf8("cat_search_btn"))
        self.verticalLayout_21.addWidget(self.cat_search_btn)
        self.verticalLayout_22.addWidget(self.groupBox_8)
        self.groupBox_12 = QtGui.QGroupBox(self.cats_tab)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.cat_add_name = QtGui.QLineEdit(self.groupBox_12)
        self.cat_add_name.setObjectName(_fromUtf8("cat_add_name"))
        self.verticalLayout_20.addWidget(self.cat_add_name)
        self.cat_add_custom_id = QtGui.QLineEdit(self.groupBox_12)
        self.cat_add_custom_id.setObjectName(_fromUtf8("cat_add_custom_id"))
        self.verticalLayout_20.addWidget(self.cat_add_custom_id)
        self.cat_add_error = QtGui.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cat_add_error.setFont(font)
        self.cat_add_error.setStyleSheet(_fromUtf8("QLabel {\n"
"color:rgb(255, 0, 0);\n"
"}"))
        self.cat_add_error.setText(_fromUtf8(""))
        self.cat_add_error.setTextFormat(QtCore.Qt.RichText)
        self.cat_add_error.setAlignment(QtCore.Qt.AlignCenter)
        self.cat_add_error.setWordWrap(True)
        self.cat_add_error.setObjectName(_fromUtf8("cat_add_error"))
        self.verticalLayout_20.addWidget(self.cat_add_error)
        self.cat_add_btn = QtGui.QPushButton(self.groupBox_12)
        self.cat_add_btn.setAutoDefault(True)
        self.cat_add_btn.setObjectName(_fromUtf8("cat_add_btn"))
        self.verticalLayout_20.addWidget(self.cat_add_btn)
        self.verticalLayout_22.addWidget(self.groupBox_12)
        self.horizontalLayout_25.addLayout(self.verticalLayout_22)
        self.books_tabs.addTab(self.cats_tab, _fromUtf8(""))
        self.gridLayout_11.addWidget(self.books_tabs, 0, 0, 1, 1)
        self.main_tabs.addWidget(self.books_tab)
        self.borrows_tab = QtGui.QWidget()
        self.borrows_tab.setObjectName(_fromUtf8("borrows_tab"))
        self.gridLayout_10 = QtGui.QGridLayout(self.borrows_tab)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.borrows_tabs = QtGui.QTabWidget(self.borrows_tab)
        self.borrows_tabs.setObjectName(_fromUtf8("borrows_tabs"))
        self.borrows_browse_tab = QtGui.QWidget()
        self.borrows_browse_tab.setObjectName(_fromUtf8("borrows_browse_tab"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.borrows_browse_tab)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.groupBox_3 = QtGui.QGroupBox(self.borrows_browse_tab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.borrow_search_id = QtGui.QLineEdit(self.groupBox_3)
        self.borrow_search_id.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.borrow_search_id.setObjectName(_fromUtf8("borrow_search_id"))
        self.horizontalLayout_17.addWidget(self.borrow_search_id)
        self.borrow_search_book_id = QtGui.QLineEdit(self.groupBox_3)
        self.borrow_search_book_id.setObjectName(_fromUtf8("borrow_search_book_id"))
        self.horizontalLayout_17.addWidget(self.borrow_search_book_id)
        self.borrow_search_book_title = QtGui.QLineEdit(self.groupBox_3)
        self.borrow_search_book_title.setObjectName(_fromUtf8("borrow_search_book_title"))
        self.horizontalLayout_17.addWidget(self.borrow_search_book_title)
        self.borrow_search_member_id = QtGui.QLineEdit(self.groupBox_3)
        self.borrow_search_member_id.setInputMethodHints(QtCore.Qt.ImhNone)
        self.borrow_search_member_id.setObjectName(_fromUtf8("borrow_search_member_id"))
        self.horizontalLayout_17.addWidget(self.borrow_search_member_id)
        self.borrow_search_member_name = QtGui.QLineEdit(self.groupBox_3)
        self.borrow_search_member_name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.borrow_search_member_name.setObjectName(_fromUtf8("borrow_search_member_name"))
        self.horizontalLayout_17.addWidget(self.borrow_search_member_name)
        self.horizontalLayout_17.setStretch(0, 1)
        self.horizontalLayout_17.setStretch(1, 2)
        self.horizontalLayout_17.setStretch(2, 2)
        self.horizontalLayout_17.setStretch(3, 2)
        self.horizontalLayout_17.setStretch(4, 2)
        self.verticalLayout_17.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_13.addWidget(self.label_3)
        self.borrow_search_start = QtGui.QDateEdit(self.groupBox_3)
        self.borrow_search_start.setCalendarPopup(True)
        self.borrow_search_start.setObjectName(_fromUtf8("borrow_search_start"))
        self.horizontalLayout_13.addWidget(self.borrow_search_start)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_13.addWidget(self.label_4)
        self.borrow_search_end = QtGui.QDateEdit(self.groupBox_3)
        self.borrow_search_end.setCalendarPopup(True)
        self.borrow_search_end.setObjectName(_fromUtf8("borrow_search_end"))
        self.horizontalLayout_13.addWidget(self.borrow_search_end)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 2)
        self.horizontalLayout_13.setStretch(2, 1)
        self.horizontalLayout_13.setStretch(3, 2)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.borrow_search_not_active = QtGui.QCheckBox(self.groupBox_3)
        self.borrow_search_not_active.setChecked(True)
        self.borrow_search_not_active.setObjectName(_fromUtf8("borrow_search_not_active"))
        self.horizontalLayout_15.addWidget(self.borrow_search_not_active)
        self.borrow_search_active = QtGui.QCheckBox(self.groupBox_3)
        self.borrow_search_active.setChecked(True)
        self.borrow_search_active.setObjectName(_fromUtf8("borrow_search_active"))
        self.horizontalLayout_15.addWidget(self.borrow_search_active)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16.setStretch(0, 2)
        self.horizontalLayout_16.setStretch(1, 1)
        self.verticalLayout_16.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_14.addWidget(self.label_11)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_14.addWidget(self.label_6)
        self.borrow_search_from = QtGui.QDateEdit(self.groupBox_3)
        self.borrow_search_from.setCalendarPopup(True)
        self.borrow_search_from.setObjectName(_fromUtf8("borrow_search_from"))
        self.horizontalLayout_14.addWidget(self.borrow_search_from)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_14.addWidget(self.label_5)
        self.borrow_search_to = QtGui.QDateEdit(self.groupBox_3)
        self.borrow_search_to.setCalendarPopup(True)
        self.borrow_search_to.setObjectName(_fromUtf8("borrow_search_to"))
        self.horizontalLayout_14.addWidget(self.borrow_search_to)
        self.horizontalLayout_14.setStretch(0, 1)
        self.horizontalLayout_14.setStretch(1, 1)
        self.horizontalLayout_14.setStretch(2, 2)
        self.horizontalLayout_14.setStretch(3, 1)
        self.horizontalLayout_14.setStretch(4, 2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_18.addLayout(self.verticalLayout_16)
        self.borrow_search_btn = QtGui.QPushButton(self.groupBox_3)
        self.borrow_search_btn.setAutoDefault(True)
        self.borrow_search_btn.setObjectName(_fromUtf8("borrow_search_btn"))
        self.horizontalLayout_18.addWidget(self.borrow_search_btn)
        self.horizontalLayout_18.setStretch(0, 4)
        self.horizontalLayout_18.setStretch(1, 1)
        self.verticalLayout_17.addLayout(self.horizontalLayout_18)
        self.verticalLayout_18.addWidget(self.groupBox_3)
        self.borrows_table = QtGui.QTableWidget(self.borrows_browse_tab)
        self.borrows_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.borrows_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.borrows_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.borrows_table.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.borrows_table.setObjectName(_fromUtf8("borrows_table"))
        self.borrows_table.setColumnCount(10)
        self.borrows_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.borrows_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.borrows_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.borrows_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.borrows_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.borrows_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.borrows_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.borrows_table.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.borrows_table.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.borrows_table.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.borrows_table.setHorizontalHeaderItem(9, item)
        self.verticalLayout_18.addWidget(self.borrows_table)
        self.borrows_tabs.addTab(self.borrows_browse_tab, _fromUtf8(""))
        self.borrows_add_tab = QtGui.QWidget()
        self.borrows_add_tab.setObjectName(_fromUtf8("borrows_add_tab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.borrows_add_tab)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.groupBox_11 = QtGui.QGroupBox(self.borrows_add_tab)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.borrow_add_book_id = QtGui.QLineEdit(self.groupBox_11)
        self.borrow_add_book_id.setObjectName(_fromUtf8("borrow_add_book_id"))
        self.horizontalLayout_22.addWidget(self.borrow_add_book_id)
        self.borrow_add_book_title = QtGui.QLineEdit(self.groupBox_11)
        self.borrow_add_book_title.setReadOnly(True)
        self.borrow_add_book_title.setObjectName(_fromUtf8("borrow_add_book_title"))
        self.horizontalLayout_22.addWidget(self.borrow_add_book_title)
        self.horizontalLayout_22.setStretch(0, 1)
        self.horizontalLayout_22.setStretch(1, 3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.borrow_add_member_id = QtGui.QLineEdit(self.groupBox_11)

        self.borrow_member = QtGui.QComboBox(self.groupBox_11)
        self.horizontalLayout_23.addWidget(self.borrow_member)

        self.borrow_add_member_id.setInputMethodHints(QtCore.Qt.ImhNone)
        self.borrow_add_member_id.setObjectName(_fromUtf8("borrow_add_member_id"))
        self.horizontalLayout_23.addWidget(self.borrow_add_member_id)
        self.borrow_add_member_name = QtGui.QLineEdit(self.groupBox_11)
        self.borrow_add_member_name.setReadOnly(True)
        self.borrow_add_member_name.setObjectName(_fromUtf8("borrow_add_member_name"))
        self.horizontalLayout_23.addWidget(self.borrow_add_member_name)
        self.horizontalLayout_23.setStretch(0, 1)
        self.horizontalLayout_23.setStretch(1, 3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_7 = QtGui.QLabel(self.groupBox_11)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_19.addWidget(self.label_7)
        self.borrow_add_start = QtGui.QDateEdit(self.groupBox_11)
        self.borrow_add_start.setCalendarPopup(True)
        self.borrow_add_start.setObjectName(_fromUtf8("borrow_add_start"))
        self.horizontalLayout_19.addWidget(self.borrow_add_start)
        self.horizontalLayout_19.setStretch(0, 1)
        self.horizontalLayout_19.setStretch(1, 15)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_8 = QtGui.QLabel(self.groupBox_11)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_20.addWidget(self.label_8)
        self.borrow_add_end = QtGui.QDateEdit(self.groupBox_11)
        self.borrow_add_end.setCalendarPopup(True)
        self.borrow_add_end.setObjectName(_fromUtf8("borrow_add_end"))
        self.horizontalLayout_20.addWidget(self.borrow_add_end)
        self.horizontalLayout_20.setStretch(0, 1)
        self.horizontalLayout_20.setStretch(1, 15)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.borrow_add_active = QtGui.QCheckBox(self.groupBox_11)
        self.borrow_add_active.setChecked(True)
        self.borrow_add_active.setObjectName(_fromUtf8("borrow_add_active"))
        self.verticalLayout_4.addWidget(self.borrow_add_active)
        self.borrow_add_error = QtGui.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.borrow_add_error.setFont(font)
        self.borrow_add_error.setStyleSheet(_fromUtf8("QLabel {\n"
"color:rgb(255, 0, 0);\n"
"}"))
        self.borrow_add_error.setText(_fromUtf8(""))
        self.borrow_add_error.setTextFormat(QtCore.Qt.RichText)
        self.borrow_add_error.setAlignment(QtCore.Qt.AlignCenter)
        self.borrow_add_error.setWordWrap(True)
        self.borrow_add_error.setObjectName(_fromUtf8("borrow_add_error"))
        self.verticalLayout_4.addWidget(self.borrow_add_error)
        self.borrow_add_btn = QtGui.QPushButton(self.groupBox_11)
        self.borrow_add_btn.setAutoDefault(True)
        self.borrow_add_btn.setObjectName(_fromUtf8("borrow_add_btn"))
        self.verticalLayout_4.addWidget(self.borrow_add_btn)
        self.gridLayout_7.addWidget(self.groupBox_11, 0, 0, 1, 1)
        self.borrows_tabs.addTab(self.borrows_add_tab, _fromUtf8(""))
        self.gridLayout_10.addWidget(self.borrows_tabs, 0, 0, 1, 1)
        self.main_tabs.addWidget(self.borrows_tab)
        self.settings_tab = QtGui.QWidget()
        self.settings_tab.setObjectName(_fromUtf8("settings_tab"))
        self.gridLayout = QtGui.QGridLayout(self.settings_tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.settings_tabs = QtGui.QTabWidget(self.settings_tab)
        self.settings_tabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.settings_tabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.settings_tabs.setObjectName(_fromUtf8("settings_tabs"))
        self.admin_tab = QtGui.QWidget()
        self.admin_tab.setObjectName(_fromUtf8("admin_tab"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.admin_tab)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.groupBox_7 = QtGui.QGroupBox(self.admin_tab)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.admin_search_id = QtGui.QLineEdit(self.groupBox_9)
        self.admin_search_id.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.admin_search_id.setObjectName(_fromUtf8("admin_search_id"))
        self.horizontalLayout_7.addWidget(self.admin_search_id)
        self.admin_search_username = QtGui.QLineEdit(self.groupBox_9)
        self.admin_search_username.setObjectName(_fromUtf8("admin_search_username"))
        self.horizontalLayout_7.addWidget(self.admin_search_username)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.admin_search_btn = QtGui.QPushButton(self.groupBox_9)
        self.admin_search_btn.setAutoDefault(True)
        self.admin_search_btn.setObjectName(_fromUtf8("admin_search_btn"))
        self.verticalLayout_7.addWidget(self.admin_search_btn)
        self.verticalLayout_8.addWidget(self.groupBox_9)
        self.admins_table = QtGui.QTableWidget(self.groupBox_7)
        self.admins_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.admins_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.admins_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.admins_table.setObjectName(_fromUtf8("admins_table"))
        self.admins_table.setColumnCount(2)
        self.admins_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.admins_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.admins_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout_8.addWidget(self.admins_table)
        self.horizontalLayout_8.addWidget(self.groupBox_7)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.groupBox_5 = QtGui.QGroupBox(self.admin_tab)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.admin_edit_username = QtGui.QLineEdit(self.groupBox_5)
        self.admin_edit_username.setEnabled(True)
        self.admin_edit_username.setReadOnly(True)
        self.admin_edit_username.setObjectName(_fromUtf8("admin_edit_username"))
        self.verticalLayout_9.addWidget(self.admin_edit_username)
        self.admin_edit_old_password = QtGui.QLineEdit(self.groupBox_5)
        self.admin_edit_old_password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.admin_edit_old_password.setText(_fromUtf8(""))
        self.admin_edit_old_password.setEchoMode(QtGui.QLineEdit.Password)
        self.admin_edit_old_password.setObjectName(_fromUtf8("admin_edit_old_password"))
        self.verticalLayout_9.addWidget(self.admin_edit_old_password)
        self.admin_edit_new_password = QtGui.QLineEdit(self.groupBox_5)
        self.admin_edit_new_password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.admin_edit_new_password.setText(_fromUtf8(""))
        self.admin_edit_new_password.setEchoMode(QtGui.QLineEdit.Password)
        self.admin_edit_new_password.setObjectName(_fromUtf8("admin_edit_new_password"))
        self.verticalLayout_9.addWidget(self.admin_edit_new_password)
        self.admin_edit_error = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.admin_edit_error.setFont(font)
        self.admin_edit_error.setStyleSheet(_fromUtf8("QLabel {\n"
"color:rgb(255, 0, 0);\n"
"}"))
        self.admin_edit_error.setText(_fromUtf8(""))
        self.admin_edit_error.setTextFormat(QtCore.Qt.RichText)
        self.admin_edit_error.setWordWrap(True)
        self.admin_edit_error.setObjectName(_fromUtf8("admin_edit_error"))
        self.verticalLayout_9.addWidget(self.admin_edit_error)
        self.admin_edit_btn = QtGui.QPushButton(self.groupBox_5)
        self.admin_edit_btn.setAutoDefault(True)
        self.admin_edit_btn.setObjectName(_fromUtf8("admin_edit_btn"))
        self.verticalLayout_9.addWidget(self.admin_edit_btn)
        self.verticalLayout_11.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.admin_tab)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.admin_add_username = QtGui.QLineEdit(self.groupBox_6)
        self.admin_add_username.setObjectName(_fromUtf8("admin_add_username"))
        self.verticalLayout_10.addWidget(self.admin_add_username)
        self.admin_add_password = QtGui.QLineEdit(self.groupBox_6)
        self.admin_add_password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.admin_add_password.setText(_fromUtf8(""))
        self.admin_add_password.setEchoMode(QtGui.QLineEdit.Password)
        self.admin_add_password.setObjectName(_fromUtf8("admin_add_password"))
        self.verticalLayout_10.addWidget(self.admin_add_password)
        self.admin_add_error = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.admin_add_error.sizePolicy().hasHeightForWidth())
        self.admin_add_error.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.admin_add_error.setFont(font)
        self.admin_add_error.setStyleSheet(_fromUtf8("QLabel {\n"
"color:rgb(255, 0, 0);\n"
"}"))
        self.admin_add_error.setText(_fromUtf8(""))
        self.admin_add_error.setTextFormat(QtCore.Qt.RichText)
        self.admin_add_error.setWordWrap(True)
        self.admin_add_error.setObjectName(_fromUtf8("admin_add_error"))
        self.verticalLayout_10.addWidget(self.admin_add_error)
        self.admin_add_btn = QtGui.QPushButton(self.groupBox_6)
        self.admin_add_btn.setAutoDefault(True)
        self.admin_add_btn.setObjectName(_fromUtf8("admin_add_btn"))
        self.verticalLayout_10.addWidget(self.admin_add_btn)
        self.verticalLayout_10.setStretch(0, 2)
        self.verticalLayout_10.setStretch(1, 2)
        self.verticalLayout_10.setStretch(2, 1)
        self.verticalLayout_10.setStretch(3, 2)
        self.verticalLayout_11.addWidget(self.groupBox_6)
        self.verticalLayout_11.setStretch(0, 1)
        self.verticalLayout_11.setStretch(1, 1)
        self.horizontalLayout_8.addLayout(self.verticalLayout_11)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 4)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_8)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/img/admin.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_tabs.addTab(self.admin_tab, icon6, _fromUtf8(""))
        self.options_tab = QtGui.QWidget()
        self.options_tab.setObjectName(_fromUtf8("options_tab"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.options_tab)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.options_other_box = QtGui.QGroupBox(self.options_tab)
        self.options_other_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.options_other_box.setObjectName(_fromUtf8("options_other_box"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.options_other_box)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.req_admin_login_edit = QtGui.QCheckBox(self.options_other_box)
        self.req_admin_login_edit.setObjectName(_fromUtf8("req_admin_login_edit"))
        self.verticalLayout_2.addWidget(self.req_admin_login_edit)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.options_other_box)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.locale_edit = QtGui.QComboBox(self.options_other_box)
        self.locale_edit.setObjectName(_fromUtf8("locale_edit"))
        self.locale_edit.addItem(_fromUtf8(""))
        self.locale_edit.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.locale_edit)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.options_other_box)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.style_edit = QtGui.QComboBox(self.options_other_box)
        self.style_edit.setObjectName(_fromUtf8("style_edit"))
        self.style_edit.addItem(_fromUtf8(""))
        self.style_edit.addItem(_fromUtf8(""))
        self.style_edit.addItem(_fromUtf8(""))
        self.style_edit.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.style_edit)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_13 = QtGui.QLabel(self.options_other_box)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_21.addWidget(self.label_13)
        self.options_edit_fine = QtGui.QLineEdit(self.options_other_box)
        self.options_edit_fine.setObjectName(_fromUtf8("options_edit_fine"))
        self.horizontalLayout_21.addWidget(self.options_edit_fine)
        self.horizontalLayout_21.setStretch(0, 1)
        self.horizontalLayout_21.setStretch(1, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_14 = QtGui.QLabel(self.options_other_box)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_24.addWidget(self.label_14)
        self.options_edit_borrow_period = QtGui.QLineEdit(self.options_other_box)
        self.options_edit_borrow_period.setObjectName(_fromUtf8("options_edit_borrow_period"))
        self.horizontalLayout_24.addWidget(self.options_edit_borrow_period)
        self.horizontalLayout_24.setStretch(0, 1)
        self.horizontalLayout_24.setStretch(1, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_24)
        self.options_edit_error = QtGui.QLabel(self.options_other_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.options_edit_error.setFont(font)
        self.options_edit_error.setStyleSheet(_fromUtf8("QLabel {\n"
"color:rgb(255, 0, 0);\n"
"}"))
        self.options_edit_error.setFrameShape(QtGui.QFrame.NoFrame)
        self.options_edit_error.setTextFormat(QtCore.Qt.RichText)
        self.options_edit_error.setWordWrap(True)
        self.options_edit_error.setObjectName(_fromUtf8("options_edit_error"))
        self.verticalLayout_2.addWidget(self.options_edit_error)
        self.options_edit_btn = QtGui.QPushButton(self.options_other_box)
        self.options_edit_btn.setObjectName(_fromUtf8("options_edit_btn"))
        self.verticalLayout_2.addWidget(self.options_edit_btn)
        self.horizontalLayout.addWidget(self.options_other_box)
        self.options_about_box = QtGui.QGroupBox(self.options_tab)
        self.options_about_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.options_about_box.setObjectName(_fromUtf8("options_about_box"))
        self.gridLayout_3 = QtGui.QGridLayout(self.options_about_box)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.textBrowser = QtGui.QTextBrowser(self.options_about_box)
        self.textBrowser.setStyleSheet(_fromUtf8("QTextBrowser {\n"
"border: None\n"
"}"))
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout_3.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.options_about_box)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_19.addLayout(self.horizontalLayout)
        self.settings_tabs.addTab(self.options_tab, icon5, _fromUtf8(""))
        self.backup_tab = QtGui.QWidget()
        self.backup_tab.setObjectName(_fromUtf8("backup_tab"))
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.backup_tab)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.options_db_box = QtGui.QGroupBox(self.backup_tab)
        self.options_db_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.options_db_box.setObjectName(_fromUtf8("options_db_box"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.options_db_box)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.db_backup_btn = QtGui.QPushButton(self.options_db_box)
        self.db_backup_btn.setObjectName(_fromUtf8("db_backup_btn"))
        self.horizontalLayout_4.addWidget(self.db_backup_btn)
        self.db_restore_btn = QtGui.QPushButton(self.options_db_box)
        self.db_restore_btn.setObjectName(_fromUtf8("db_restore_btn"))
        self.horizontalLayout_4.addWidget(self.db_restore_btn)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.line_9 = QtGui.QFrame(self.options_db_box)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.horizontalLayout_6.addWidget(self.line_9)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_12 = QtGui.QLabel(self.options_db_box)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_5.addWidget(self.label_12)
        self.db_csv_export_table = QtGui.QComboBox(self.options_db_box)
        self.db_csv_export_table.setObjectName(_fromUtf8("db_csv_export_table"))
        self.db_csv_export_table.addItem(_fromUtf8(""))
        self.db_csv_export_table.addItem(_fromUtf8(""))
        self.db_csv_export_table.addItem(_fromUtf8(""))
        self.db_csv_export_table.addItem(_fromUtf8(""))
        self.db_csv_export_table.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.db_csv_export_table)
        self.db_csv_export_btn = QtGui.QPushButton(self.options_db_box)
        self.db_csv_export_btn.setObjectName(_fromUtf8("db_csv_export_btn"))
        self.horizontalLayout_5.addWidget(self.db_csv_export_btn)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.db_error = QtGui.QLabel(self.options_db_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.db_error.setFont(font)
        self.db_error.setStyleSheet(_fromUtf8("QLabel {\n"
"color:rgb(255, 0, 0);\n"
"}"))
        self.db_error.setText(_fromUtf8(""))
        self.db_error.setTextFormat(QtCore.Qt.RichText)
        self.db_error.setWordWrap(True)
        self.db_error.setObjectName(_fromUtf8("db_error"))
        self.verticalLayout_3.addWidget(self.db_error)
        self.verticalLayout_24.addWidget(self.options_db_box)
        self.groupBox_13 = QtGui.QGroupBox(self.backup_tab)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.backup_on_exit = QtGui.QCheckBox(self.groupBox_13)
        self.backup_on_exit.setObjectName(_fromUtf8("backup_on_exit"))
        self.verticalLayout_23.addWidget(self.backup_on_exit)
        self.backup_csv_files = QtGui.QCheckBox(self.groupBox_13)
        self.backup_csv_files.setObjectName(_fromUtf8("backup_csv_files"))
        self.verticalLayout_23.addWidget(self.backup_csv_files)
        self.backup_db_file = QtGui.QCheckBox(self.groupBox_13)
        self.backup_db_file.setObjectName(_fromUtf8("backup_db_file"))
        self.verticalLayout_23.addWidget(self.backup_db_file)
        self.cloud_backup_error = QtGui.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cloud_backup_error.setFont(font)
        self.cloud_backup_error.setStyleSheet(_fromUtf8("QLabel {\n"
"color:rgb(255, 0, 0);\n"
"}"))
        self.cloud_backup_error.setText(_fromUtf8(""))
        self.cloud_backup_error.setTextFormat(QtCore.Qt.RichText)
        self.cloud_backup_error.setWordWrap(True)
        self.cloud_backup_error.setObjectName(_fromUtf8("cloud_backup_error"))
        self.verticalLayout_23.addWidget(self.cloud_backup_error)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.cloud_backup_save_btn = QtGui.QPushButton(self.groupBox_13)
        self.cloud_backup_save_btn.setObjectName(_fromUtf8("cloud_backup_save_btn"))
        self.horizontalLayout_30.addWidget(self.cloud_backup_save_btn)
        self.cloud_backup_btn = QtGui.QPushButton(self.groupBox_13)
        self.cloud_backup_btn.setObjectName(_fromUtf8("cloud_backup_btn"))
        self.horizontalLayout_30.addWidget(self.cloud_backup_btn)
        self.verticalLayout_23.addLayout(self.horizontalLayout_30)
        self.verticalLayout_24.addWidget(self.groupBox_13)
        self.settings_tabs.addTab(self.backup_tab, _fromUtf8(""))
        self.gridLayout.addWidget(self.settings_tabs, 0, 0, 1, 1)
        self.main_tabs.addWidget(self.settings_tab)
        self.horizontalLayout_9.addWidget(self.main_tabs)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.log_viewer = QtGui.QPlainTextEdit(self.centralwidget)
        self.log_viewer.setMaximumSize(QtCore.QSize(16777215, 40))
        self.log_viewer.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.log_viewer.setReadOnly(True)
        self.log_viewer.setObjectName(_fromUtf8("log_viewer"))
        self.verticalLayout_5.addWidget(self.log_viewer)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.main_tabs.setCurrentIndex(0)
        self.members_tabs.setCurrentIndex(1)
        self.books_tabs.setCurrentIndex(0)
        self.borrows_tabs.setCurrentIndex(0)
        self.settings_tabs.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MeX LMS", None))
        __sortingEnabled = self.nav_list.isSortingEnabled()
        self.nav_list.setSortingEnabled(False)
        item = self.nav_list.item(0)
        item.setText(_translate("MainWindow", "Home", None))
        item = self.nav_list.item(1)
        item.setText(_translate("MainWindow", "Members", None))
        item = self.nav_list.item(2)
        item.setText(_translate("MainWindow", "Books", None))
        item = self.nav_list.item(3)
        item.setText(_translate("MainWindow", "Borrow", None))
        item = self.nav_list.item(4)
        item.setText(_translate("MainWindow", "Settings", None))
        self.nav_list.setSortingEnabled(__sortingEnabled)
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/img/img/logo.png\" width=\"500\" /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.groupBox.setTitle(_translate("MainWindow", "Search", None))
        self.member_search_id.setPlaceholderText(_translate("MainWindow", "ID", None))
        self.member_search_name.setPlaceholderText(_translate("MainWindow", "Name", None))
        self.member_search_email.setPlaceholderText(_translate("MainWindow", "Email", None))
        self.member_search_mob.setPlaceholderText(_translate("MainWindow", "Mobile No.", None))
        self.member_search_btn.setText(_translate("MainWindow", "Search", None))
        item = self.members_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.members_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.members_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "fine", None))
        item = self.members_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Email", None))
        item = self.members_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Mobile", None))
        item = self.members_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Note", None))
        self.members_tabs.setTabText(self.members_tabs.indexOf(self.members_browse_tab), _translate("MainWindow", "Browse Members", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Add Member", None))
        self.member_add_name.setPlaceholderText(_translate("MainWindow", "Name", None))
        self.member_add_email.setPlaceholderText(_translate("MainWindow", "Email", None))
        self.member_add_mob.setPlaceholderText(_translate("MainWindow", "Mobile No.", None))
        self.member_add_btn.setText(_translate("MainWindow", "Add Member", None))
        self.members_tabs.setTabText(self.members_tabs.indexOf(self.members_add_tab), _translate("MainWindow", "Add member", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Search", None))
        self.book_search_id.setPlaceholderText(_translate("MainWindow", "ID", None))
        self.book_search_title.setPlaceholderText(_translate("MainWindow", "Title", None))
        self.book_search_author.setPlaceholderText(_translate("MainWindow", "Author", None))
        self.book_search_available.setText(_translate("MainWindow", "Available", None))
        self.book_search_not_available.setText(_translate("MainWindow", "Not Available", None))
        self.label_15.setText(_translate("MainWindow", "Category:", None))
        self.book_search_cat_id.setPlaceholderText(_translate("MainWindow", "ID", None))
        self.book_search_cat_custom_id.setPlaceholderText(_translate("MainWindow", "Custom ID", None))
        self.book_search_cat_order.setPlaceholderText(_translate("MainWindow", "Book order in category", None))
        self.book_search_btn.setText(_translate("MainWindow", "Search", None))
        item = self.books_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.books_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title", None))
        item = self.books_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Available", None))
        item = self.books_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Copies", None))
        item = self.books_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Author", None))
        item = self.books_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Category", None))
        item = self.books_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "State", None))
        self.books_tabs.setTabText(self.books_tabs.indexOf(self.books_browse_tab), _translate("MainWindow", "Browse Books", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Add Book", None))
        self.book_add_title.setPlaceholderText(_translate("MainWindow", "Title", None))
        self.book_add_author.setPlaceholderText(_translate("MainWindow", "Author", None))
        self.label_9.setText(_translate("MainWindow", "Category:", None))
        self.book_add_cat_id.setPlaceholderText(_translate("MainWindow", "ID", None))
        self.book_add_cat_custom_id.setPlaceholderText(_translate("MainWindow", "Custom ID", None))
        self.book_add_cat_order.setPlaceholderText(_translate("MainWindow", "Book order in category", None))
        self.label_10.setText(_translate("MainWindow", "State:", None))
        self.book_add_copies.setPlaceholderText(_translate("MainWindow", "No. of copies", None))
        self.book_add_available.setText(_translate("MainWindow", "Available", None))
        self.book_add_btn.setText(_translate("MainWindow", "Add Book", None))
        self.books_tabs.setTabText(self.books_tabs.indexOf(self.Books_add_tab), _translate("MainWindow", "Add Book", None))
        item = self.cats_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.cats_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.cats_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Custom ID", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Search", None))
        self.cat_search_id.setPlaceholderText(_translate("MainWindow", "ID", None))
        self.cat_search_name.setPlaceholderText(_translate("MainWindow", "Name", None))
        self.cat_search_custom_id.setPlaceholderText(_translate("MainWindow", "Custom ID", None))
        self.cat_search_btn.setText(_translate("MainWindow", "Search", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "Add Category", None))
        self.cat_add_name.setPlaceholderText(_translate("MainWindow", "Name", None))
        self.cat_add_custom_id.setPlaceholderText(_translate("MainWindow", "Custom ID", None))
        self.cat_add_btn.setText(_translate("MainWindow", "Add", None))
        self.books_tabs.setTabText(self.books_tabs.indexOf(self.cats_tab), _translate("MainWindow", "Categories", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Search", None))
        self.borrow_search_id.setPlaceholderText(_translate("MainWindow", "ID", None))
        self.borrow_search_book_id.setPlaceholderText(_translate("MainWindow", "Book ID", None))
        self.borrow_search_book_title.setPlaceholderText(_translate("MainWindow", "Book Title", None))
        self.borrow_search_member_id.setPlaceholderText(_translate("MainWindow", "Member ID", None))
        self.borrow_search_member_name.setPlaceholderText(_translate("MainWindow", "Member Name", None))
        self.label_3.setText(_translate("MainWindow", "Start", None))
        self.label_4.setText(_translate("MainWindow", "End", None))
        self.borrow_search_not_active.setText(_translate("MainWindow", "Not Active", None))
        self.borrow_search_active.setText(_translate("MainWindow", "Active", None))
        self.label_11.setText(_translate("MainWindow", "Time period:", None))
        self.label_6.setText(_translate("MainWindow", "From", None))
        self.label_5.setText(_translate("MainWindow", "To", None))
        self.borrow_search_btn.setText(_translate("MainWindow", "Search", None))
        item = self.borrows_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.borrows_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Book ID", None))
        item = self.borrows_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Book Title", None))
        item = self.borrows_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Member ID", None))
        item = self.borrows_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Member Name", None))
        item = self.borrows_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Start", None))
        item = self.borrows_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "End", None))
        item = self.borrows_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Active", None))
        item = self.borrows_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Created By", None))
        item = self.borrows_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Updated By", None))
        self.borrows_tabs.setTabText(self.borrows_tabs.indexOf(self.borrows_browse_tab), _translate("MainWindow", "Browse Borrows", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "Add Borrow", None))
        self.borrow_add_book_id.setPlaceholderText(_translate("MainWindow", "Book ID", None))
        self.borrow_add_book_title.setPlaceholderText(_translate("MainWindow", "Book Title", None))
        self.borrow_add_member_id.setPlaceholderText(_translate("MainWindow", "Member ID", None))
        self.borrow_add_member_name.setPlaceholderText(_translate("MainWindow", "Member Name", None))
        self.label_7.setText(_translate("MainWindow", "Start", None))
        self.label_8.setText(_translate("MainWindow", "End", None))
        self.borrow_add_active.setText(_translate("MainWindow", "Active", None))
        self.borrow_add_btn.setText(_translate("MainWindow", "Add Borrow", None))
        self.borrows_tabs.setTabText(self.borrows_tabs.indexOf(self.borrows_add_tab), _translate("MainWindow", "Add Borrow", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Admins", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Search", None))
        self.admin_search_id.setPlaceholderText(_translate("MainWindow", "ID", None))
        self.admin_search_username.setPlaceholderText(_translate("MainWindow", "username", None))
        self.admin_search_btn.setText(_translate("MainWindow", "Search", None))
        item = self.admins_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.admins_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "username", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Current Admin", None))
        self.admin_edit_username.setPlaceholderText(_translate("MainWindow", "username", None))
        self.admin_edit_old_password.setPlaceholderText(_translate("MainWindow", "old password", None))
        self.admin_edit_new_password.setPlaceholderText(_translate("MainWindow", "new password", None))
        self.admin_edit_btn.setText(_translate("MainWindow", "Update Info", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Add Admin", None))
        self.admin_add_username.setPlaceholderText(_translate("MainWindow", "username", None))
        self.admin_add_password.setPlaceholderText(_translate("MainWindow", "password", None))
        self.admin_add_btn.setText(_translate("MainWindow", "Add Admin", None))
        self.settings_tabs.setTabText(self.settings_tabs.indexOf(self.admin_tab), _translate("MainWindow", "Adminstration", None))
        self.options_other_box.setTitle(_translate("MainWindow", "Other Options", None))
        self.req_admin_login_edit.setText(_translate("MainWindow", "Request admin login on startup", None))
        self.label.setText(_translate("MainWindow", "Language:", None))
        self.locale_edit.setItemText(0, _translate("MainWindow", "Arabic", None))
        self.locale_edit.setItemText(1, _translate("MainWindow", "English", None))
        self.label_2.setText(_translate("MainWindow", "Style:", None))
        self.style_edit.setItemText(0, _translate("MainWindow", "Default", None))
        self.style_edit.setItemText(1, _translate("MainWindow", "Dark Orange", None))
        self.style_edit.setItemText(2, _translate("MainWindow", "Dark Green", None))
        self.style_edit.setItemText(3, _translate("MainWindow", "Dark Blue", None))
        self.label_13.setText(_translate("MainWindow", "Fine unit (EGP/daylate):", None))
        self.options_edit_fine.setPlaceholderText(_translate("MainWindow", "Fine Per Day", None))
        self.label_14.setText(_translate("MainWindow", "Default Borrow period (days): ", None))
        self.options_edit_borrow_period.setPlaceholderText(_translate("MainWindow", "default borrow period (days)", None))
        self.options_edit_btn.setText(_translate("MainWindow", "Save", None))
        self.options_about_box.setTitle(_translate("MainWindow", "About", None))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:600;\">MeX Library Manegement System</span><span style=\" font-family:\'Cantarell\'; font-size:11pt;\"> is free open source software developed by: </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Cantarell\'; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'arial,helvetica,sans-serif\'; font-size:10pt; font-weight:600; color:#000000;\">Mahmoud Elshobaky</span><span style=\" font-family:\'arial,helvetica,clean,sans-serif\'; font-size:10pt; font-weight:600; color:#808080;\"> </span><span style=\" font-family:\'verdana,sans-serif\'; font-size:11pt; font-weight:600; color:#ff6600;\"><br /></span><span style=\" font-family:\'verdana,sans-serif\'; font-size:11pt; font-weight:600; color:#ff6600; vertical-align:sub;\">| e-mail :</span><span style=\" font-family:\'verdana,sans-serif\'; font-size:9pt; color:#00557f;\"> </span><a href=\"mailto:mahmoud.elshobaky@gmail.com\"><span style=\" font-family:\'Cantarell\'; font-size:9pt; text-decoration: underline; color:#00557f;\">mahmoud.elshobaky@gmail.com</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'verdana,sans-serif\'; font-size:10pt; font-weight:600; color:#ff5500; vertical-align:sub;\">| LinkedIn :</span><span style=\" font-family:\'verdana,sans-serif\'; font-size:9pt; color:#00557f; vertical-align:sub;\"> </span><a href=\"https://www.linkedin.com/in/mahmoudelshobaky\"><span style=\" font-family:\'Cantarell\'; font-size:9pt; text-decoration: underline; color:#00557f;\">mahmoudelshobaky</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'verdana,sans-serif\'; font-size:10pt; font-weight:600; color:#ff5500; vertical-align:sub;\">| GitHub :</span><span style=\" font-family:\'verdana,sans-serif\'; font-size:9pt; color:#00557f; vertical-align:sub;\"> </span><a href=\"https://github.com/elshobaky\"><span style=\" font-family:\'Cantarell\'; font-size:9pt; text-decoration: underline; color:#00557f;\">elshobaky</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'verdana,sans-serif\'; font-size:11pt; text-decoration: underline; color:#1155cc;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'verdana,sans-serif\'; font-size:9pt; color:#5555ff;\">*For developers : feel free to contibute to</span><span style=\" font-family:\'verdana,sans-serif\'; font-size:9pt; color:#00aa7f;\"> </span><a href=\"https://github.com/elshobaky/MeX-LMS\"><span style=\" font-family:\'Cantarell\'; font-size:9pt; font-weight:600; text-decoration: underline; color:#00aa7f;\">MeX-LMS project on GitHub</span></a></p></body></html>", None))
        self.settings_tabs.setTabText(self.settings_tabs.indexOf(self.options_tab), _translate("MainWindow", "Options", None))
        self.options_db_box.setTitle(_translate("MainWindow", "Manual Backup", None))
        self.db_backup_btn.setText(_translate("MainWindow", "Backup", None))
        self.db_restore_btn.setText(_translate("MainWindow", "Restore", None))
        self.label_12.setText(_translate("MainWindow", "Export to csv:", None))
        self.db_csv_export_table.setItemText(0, _translate("MainWindow", "Entire Database", None))
        self.db_csv_export_table.setItemText(1, _translate("MainWindow", "Members", None))
        self.db_csv_export_table.setItemText(2, _translate("MainWindow", "Books", None))
        self.db_csv_export_table.setItemText(3, _translate("MainWindow", "Borrows", None))
        self.db_csv_export_table.setItemText(4, _translate("MainWindow", "Admins", None))
        self.db_csv_export_btn.setText(_translate("MainWindow", "Export", None))
        self.groupBox_13.setTitle(_translate("MainWindow", "Cloud Backup", None))
        self.backup_on_exit.setText(_translate("MainWindow", "Auto Backup before closing", None))
        self.backup_csv_files.setText(_translate("MainWindow", "Backup CSV Files", None))
        self.backup_db_file.setText(_translate("MainWindow", "Backup Database File", None))
        self.cloud_backup_save_btn.setText(_translate("MainWindow", "Save", None))
        self.cloud_backup_btn.setText(_translate("MainWindow", "Backup Now", None))
        self.settings_tabs.setTabText(self.settings_tabs.indexOf(self.backup_tab), _translate("MainWindow", "Backup", None))

import resources_rc
