# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/memberedit.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MemberEdit(object):
    def setupUi(self, MemberEdit):
        MemberEdit.setObjectName(_fromUtf8("MemberEdit"))
        MemberEdit.resize(511, 443)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/img/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MemberEdit.setWindowIcon(icon)
        MemberEdit.setStyleSheet(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(MemberEdit)
        self.label_6.setGeometry(QtCore.QRect(150, 10, 211, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_6.setFrameShadow(QtGui.QFrame.Plain)
        self.label_6.setLineWidth(1)
        self.label_6.setMidLineWidth(0)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.layoutWidget = QtGui.QWidget(MemberEdit)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 100, 471, 241))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setFrameShadow(QtGui.QFrame.Plain)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_7.addWidget(self.label)
        self.member_edit_id = QtGui.QLineEdit(self.layoutWidget)
        self.member_edit_id.setReadOnly(True)
        self.member_edit_id.setObjectName(_fromUtf8("member_edit_id"))
        self.horizontalLayout_7.addWidget(self.member_edit_id)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtGui.QFrame.Plain)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        self.member_edit_name = QtGui.QLineEdit(self.layoutWidget)
        self.member_edit_name.setObjectName(_fromUtf8("member_edit_name"))
        self.horizontalLayout_6.addWidget(self.member_edit_name)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtGui.QFrame.Plain)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.member_edit_email = QtGui.QLineEdit(self.layoutWidget)
        self.member_edit_email.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.member_edit_email.setObjectName(_fromUtf8("member_edit_email"))
        self.horizontalLayout_5.addWidget(self.member_edit_email)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_4.setFrameShadow(QtGui.QFrame.Plain)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.member_edit_mob = QtGui.QLineEdit(self.layoutWidget)
        self.member_edit_mob.setInputMethodHints(QtCore.Qt.ImhNone)
        self.member_edit_mob.setObjectName(_fromUtf8("member_edit_mob"))
        self.horizontalLayout_4.addWidget(self.member_edit_mob)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_5.setFrameShadow(QtGui.QFrame.Plain)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.member_edit_fine = QtGui.QLineEdit(self.layoutWidget)
        self.member_edit_fine.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.member_edit_fine.setText(_fromUtf8(""))
        self.member_edit_fine.setObjectName(_fromUtf8("member_edit_fine"))
        self.horizontalLayout_3.addWidget(self.member_edit_fine)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_7.setFrameShadow(QtGui.QFrame.Plain)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.member_edit_note = QtGui.QPlainTextEdit(self.layoutWidget)
        self.member_edit_note.setObjectName(_fromUtf8("member_edit_note"))
        self.horizontalLayout.addWidget(self.member_edit_note)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 3)
        self.layoutWidget1 = QtGui.QWidget(MemberEdit)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 350, 431, 81))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.member_edit_error = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.member_edit_error.setFont(font)
        self.member_edit_error.setText(_fromUtf8(""))
        self.member_edit_error.setAlignment(QtCore.Qt.AlignCenter)
        self.member_edit_error.setObjectName(_fromUtf8("member_edit_error"))
        self.verticalLayout_2.addWidget(self.member_edit_error)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.member_delete_btn = QtGui.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.member_delete_btn.setFont(font)
        self.member_delete_btn.setCheckable(False)
        self.member_delete_btn.setAutoDefault(True)
        self.member_delete_btn.setObjectName(_fromUtf8("member_delete_btn"))
        self.horizontalLayout_2.addWidget(self.member_delete_btn)
        self.member_edit_cancel_btn = QtGui.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.member_edit_cancel_btn.setFont(font)
        self.member_edit_cancel_btn.setAutoDefault(True)
        self.member_edit_cancel_btn.setObjectName(_fromUtf8("member_edit_cancel_btn"))
        self.horizontalLayout_2.addWidget(self.member_edit_cancel_btn)
        self.member_edit_btn = QtGui.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.member_edit_btn.setFont(font)
        self.member_edit_btn.setAutoDefault(True)
        self.member_edit_btn.setFlat(False)
        self.member_edit_btn.setObjectName(_fromUtf8("member_edit_btn"))
        self.horizontalLayout_2.addWidget(self.member_edit_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 1)
        self.borrow_book_btn = QtGui.QPushButton(MemberEdit)
        self.borrow_book_btn.setGeometry(QtCore.QRect(190, 70, 121, 23))
        self.borrow_book_btn.setObjectName(_fromUtf8("borrow_book_btn"))

        self.retranslateUi(MemberEdit)
        QtCore.QMetaObject.connectSlotsByName(MemberEdit)

    def retranslateUi(self, MemberEdit):
        MemberEdit.setWindowTitle(_translate("MemberEdit", "MeX LMS - Edit Member", None))
        self.label_6.setText(_translate("MemberEdit", "Edit Member", None))
        self.label.setText(_translate("MemberEdit", "ID", None))
        self.member_edit_id.setPlaceholderText(_translate("MemberEdit", "ID", None))
        self.label_2.setText(_translate("MemberEdit", "Name", None))
        self.member_edit_name.setPlaceholderText(_translate("MemberEdit", "Name", None))
        self.label_3.setText(_translate("MemberEdit", "Email", None))
        self.member_edit_email.setPlaceholderText(_translate("MemberEdit", "Email", None))
        self.label_4.setText(_translate("MemberEdit", "Mob no.", None))
        self.member_edit_mob.setPlaceholderText(_translate("MemberEdit", "Mobile number", None))
        self.label_5.setText(_translate("MemberEdit", "Fine", None))
        self.member_edit_fine.setPlaceholderText(_translate("MemberEdit", "Fine", None))
        self.label_7.setText(_translate("MemberEdit", "Note", None))
        self.member_delete_btn.setText(_translate("MemberEdit", "Delete", None))
        self.member_edit_cancel_btn.setText(_translate("MemberEdit", "Close", None))
        self.member_edit_btn.setText(_translate("MemberEdit", "Save", None))
        self.borrow_book_btn.setText(_translate("MemberEdit", "Borrrow a book", None))

import resources_rc
